### ISSUE TITLE
Unique slug per character

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectA#100]
We're currently generating slugs for URL paths like `/sentiment/tyrion-lannister` which is nicer than using the ID or the URL-escaped name.
It should be included in the DB to make it consistent between all projects.

Schema:

```
// slug for character (unique ID for URL generated from name)
slug: {type: String, required: true, unique: true},
```

We currently generate them like this with the [slug package](https://www.npmjs.com/package/slug):

``` js
slug = require('slug');
// ...
"slug": slug(character.name, {lower: true}) 
```

**Comment by boriside** [comment]
Aaaaand we have issue #100!!!

**Comment by boriside** [comment]
@julienschmidt is it only for character or should we do it also for other models?

**Comment by julienschmidt** [comment]
We only need it for characters, but it can't hurt to add it to all models (where it makes sense) :wink:

**Comment by togiberlin** [comment]
@boriside Then let's only add it for character model for time being. If you need more, just write into this issue.

**Comment by boriside** [comment]
ok, done. Then close (for now)

**Comment by julienschmidt** [comment]
You added the line to the Schema, but you're not generating the slug...

**Comment by ghost** [comment]
I am not aware of this whole discussion, but isn´t #102 referencing the same purpose, but with another implementation?

@kordianbruck @sacdallago

**Comment by kordianbruck** [comment]
@Adiolis I actually quit this discussion cause I have no clue about it. But yea, now that I actually understand what the "slug" is, I think it is the same as #102

**Comment by sacdallago** [comment]
As far as I understood this slog is _where_ you get the data from aka: permalink of the wiki page. But now you question my understanding

**Comment by ghost** [comment]
`slug('Jon Snow', {lower: true})` as proposed will not give the wiki link http://awoiaf.westeros.org/index.php/Jon_Snow for example.

I think this is just about identifying db entries.

**Comment by julienschmidt** [comment]
`slug('Jon Snow', {lower: true})` will return `jon-snow`. If you really want it to be consistent with the wiki, you should provide the same Slug the wiki uses instead.

**Comment by sacdallago** [comment]
I see where this is going. Yes. Same as MD5 story but on a SEO level.

Necessarily? Why? Highly redundant if you ask me

**Comment by sacdallago** [comment]
Oh sorry. I should have read the title of the issue. Shit. Shit. @kordianbruck is right this, as MD5 are redundant, but they eventually become necessary... Implement either of them please, I personally like MD5 more

**Comment by ghost** [comment]
I removed the slug form the model, because no filling is working until the required slug is implemented, which is actually not the case.
Please add this required field after implementing this!

**Comment by sacdallago** [comment]
so what is it gonna be in the end? Slug, MD5?

**Comment by ghost** [comment]
@sacdallago Could you please explain to me, why you like md5 more?
I have no clue, which one to use. Slugs are for me at least human-readable. Probably it would also be a nice idea to just use the wiki slug.

@kordianbruck

**Comment by sacdallago** [comment]
To me MD5 conveys that sense of comfort and love which cannot be rationally explained. Like the love for @kordianbruck :laughing: :laughing: :laughing: :laughing: 

No, but seriously: I deal with variable size input. MD5s become a pretty precise and concise representation of [very long text sequences](http://www.ncbi.nlm.nih.gov/nuccore/667677333?report=fasta). They are my _human-readable_.

But you have other things to take care of, like capital and lower case letters, so chose whatever you prefer, I don't care as long as it works for all of you (and me) :D

**Comment by julienschmidt** [comment]
With the small difference that we're not dealing with megabytes of sequences of just 4 letters but with names - which tend to be human-readable.

I prefer all-lowercase URLs, but reusing the slugs from the wiki might be the best option.

**Comment by julienschmidt** [comment]
If we have mixed-case slugs, we probably need a function to make a case-insensitive lookups too :stuck_out_tongue_closed_eyes:

**Comment by ghost** [comment]
I would now just use the slugs from the wiki.
@julienschmidt Is this a big issue for your project to change to them?

**Comment by julienschmidt** [comment]
nope, as long as they also work as filenames, we're fine with whatever string.

**Comment by ghost** [comment]
@kordianbruck Please update. npm run update --collection=characters .
Just restart if connections are refused.

**Comment by kordianbruck** [comment]
Done.
