### ISSUE TITLE
Getting character by md5(name)

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectA#102]
Me and @mammuth were suggesting the following : 
- Based on the assumption that in production mode, database wont be repopulated that often( maybe never?)
- Since the user is navigating inside our app with the characterId we got from the API, the calls will be consistent with characterId (i.e.  Because the id's we use for querying eg.  A character are the ones we got some seconds ago when we queried all characters for the listing)
- This will solve the hassle with the name
- no extra implementation from your side 

Cons
- user copies the character detail link somewhere and database is repopulated, the characterId changes and link not available anymore
- some implications for SEO also if database repopulated

The question is how often will the database be repopulated and the Ids changed ?

**Comment by ghost** [comment]
If in production the refill policy is never used, but the update one, then the _id will never change.
See https://github.com/Rostlab/JS16_ProjectA#scraping-and-filling-the-database .
I see no reason to use the refill policy in later parts...

Other possibility is to use the name of the character as identifier since it is always unique. (strict mode for getByName will be implemented soon/today :P ). For references in the database we also use the name...

**Comment by sacdallago** [comment]
I am **strongly** against getting char by _id if you store the id's somewhere indefinitely. I have advised everyone up until now to not go by _id, because the different projects need to be as independent as possible. Sure: if you get the entire content of the character store from the API and _in runtime_ use those _id's then this is perfectly acceptable, because it's extremely unlikely that the _id's change and if that would be the case, the user would just have to re-load the page. But if you construct your app upon _id's existing now, and store them in, for example, localStorage, without ever reloading them... Well.. Then I fear you'll run into trouble!

**Comment by gyachdav** [comment]
@sacdallago is right _id should never be used. It's an internal identifier that only has meaning within the context of the database and completely meaningless anywhere else. Also the assumption that the _id is immutable is wrong - You should expect it to change and it will. 

Now, you have enough capabilities baked into the API to retrieve char data. That's alexactly what an API is for (Remember seperation of concerns). If the API lacks some of the functionalities your app requires then you need to request a new feature. But based on @adiolis response seems like you should have no problem using the chat name as an unique identifier 

Finally I saw somewhere that you plan an autocomplete for char names feature. Check with C10 they have already implemented this one.

**Comment by kordianbruck** [comment]
@mina-zaki md5(Name)  maybe instead?

**Comment by sacdallago** [comment]
@kordianbruck that's fucking awesome, how did I not come up with that

**Comment by mina-kleid** [comment]
@kordianbruck That is great, so we dont fall into the hassle of encoding urls and so on. once you decide on it let me know so we can change our calls

**Comment by kordianbruck** [comment]
Reopening this issue so we can talk this through more. 

We would need to save the MD5 along with the name in the DB and it might create inconsistencies, or  we can even replace the internal mongoDB _id with the md5 of the name, so we can use proper references - what are your thoughts?

Whenever we are updating a name we would need to also update the MD5.

**Comment by sacdallago** [comment]
@kordianbruck I think you can overcome much of the complexity using mongo's inbuild functions:
https://docs.mongodb.org/manual/reference/operator/query/where/

Something like: `where md5(this.name) == request.md5`

**Comment by kordianbruck** [comment]
@sacdallago great idea, now we have a API operation that will heat the LRZ to Sauna-temperature© with every call. :tada: 

Calculating the MD5 for 2000 Characters with each query is really not a good idea...

**Comment by sacdallago** [comment]
HA. They've got computing time :D :D but good point. We are back to the ancient problem:    

:boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom:

### redundancy vs CPU time

:boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom:     

Just store the MD5 in the char document when scraping it then? I **think** you can actually also set the default moongose value to md5 hash the name attribute and bam: problem solved?

P.S.: I like saunas
P.P.S.: I like saunas with computers :heart:

**Comment by ghost** [comment]
@kordianbruck Are you on this?
I could not follow the whole discussion here and have a bunch of other things to do...

**Comment by kordianbruck** [comment]
@Adiolis @mina-zaki  it depends if it still makes sense to change this at this stage. Do you still need it @mina-zaki ?

**Comment by julienschmidt** [comment]
Yes @Adiolis that seems to be basically the same problem as #100 

Using hashes is a bad idea from a usability and SEO point of view. I think [Slugs](https://en.wikipedia.org/wiki/Semantic_URL#Slug) / #100 is what you are looking for.

**Comment by kordianbruck** [comment]
@julienschmidt SEO in an API? really? :boom: :bomb: 
ad Usability: users use the frontend, not the backend API.

**Comment by ghost** [comment]
I don´t get why we should transform the unique name on the api in first place? (no matter if slug or hash)

**Comment by julienschmidt** [comment]
@kordianbruck this is not about the API but being able the identify a certain object (character) from user input (the URL) without passing the DB-specific _id around.
Ideally every subproject would use the same _human readable_  valid URL path fragment (So no `Jon Snow (grandchild of whatever II)` to identify those objects. That's what #100 is about. I must admit that I didn't read the whole discussion here (and don't intend to).

**Comment by ghost** [comment]
Well, implementation #100 is chosen for this purpose.

**Comment by sacdallago** [comment]
:D you just liked the number
