### ISSUE TITLE
Characters Missing

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#105]
In your database some characters are missing like Robert Baratheon or Brienne of Tarth.

https://github.com/Rostlab/JS16_ProjectC_Group10/issues/185

**Comment by ghost** [comment]
@theocheslerean the scraper is not returning them.
Probably because of redirects in the wiki?

**Comment by gyachdav** [comment]
http://awoiaf.westeros.org/index.php/Robert_Baratheon
redirects to
http://awoiaf.westeros.org/index.php/Robert_I_Baratheon

Is the scraper not following redirects? if not then we might be missing a bunch of characters. 

e.g. 
http://awoiaf.westeros.org/index.php/Brienne_of_Tarth
redirects to
http://awoiaf.westeros.org/index.php/Brienne_Tarth

**Comment by ghost** [comment]
Seems to be fixed. Please update, @kordianbruck

**Comment by kordianbruck** [comment]
@Adiolis refill or update? I already updated it...

**Comment by kordianbruck** [comment]
Done.

**Comment by bandle** [comment]
I tested it with Brienne of Tarth and it didn't work :/

https://got-api.bruck.me/api/characters/brienne
also 
robert doesn't work (There is no Baratheon)
https://got-api.bruck.me/api/characters/robert

**Comment by ghost** [comment]
I get on my local db:
`{"message":"Success","data":{"_id":"56f2dac36e157f8dac6527e2","imageLink":"/misc/images/characters/Brienne_of_Tarth.jpeg","male":false,"dateOfBirth":280,"house":"House Tarth","slug":"Brienne_of_Tarth","name":"Brienne of Tarth","__v":0,"pageRank":278,"books":["A Clash of Kings","A Storm of Swords","A Feast for Crows","A Dance with Dragons"],"updatedAt":"2016-03-23T20:07:08.848Z","createdAt":"2016-03-23T18:04:51.113Z","titles":[]}}`

Probably @kordianbruck didn´t refill?

**Comment by bandle** [comment]
Very likely yes. The live version does feature slug as well

**Comment by kordianbruck** [comment]
@mbandle works now :3 :fire_engine: 
I did refill, back then but dunno why its really missing...
