### ISSUE TITLE
API for character status (dead/alive)

### ISSUE THREAD

**Issue by nicoladesocio** [Rostlab/JS16_ProjectA#106]
Hello,

project F needs an API to get only the charachters with status alive, so that the PLOD for dead characters is not displayed.

I coded some functions in npm, please check https://github.com/Rostlab/JS16_ProjectB_Group7/pull/22

**Comment by kordianbruck** [comment]
@togiberlin why do we need a new field? We could simply check this on output and add a flag, based upon the fact if a deathDate is saved for this character.

@nicoladesocio can you not simply check if the character has a deathDate and filter by that?

**Comment by ghost** [comment]
Should be no problem to calculate and add such a flag right before the response. I would not store that in an extra field, that can have inconsistencies.

**Comment by kordianbruck** [comment]
@Adiolis I don't even think we need a flag. Project F should simply check if the character has a death date. I think this issue is obsolete.

**Comment by ghost** [comment]
@sacdallago @nicoladesocio

**Comment by sacdallago** [comment]
@kordianbruck 's right. Having a death date is good enough a check
