### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectA#107]
Muchachos, 

Your feature freeze is March 25th and delivery is April 3rd. You're the foundations we are all standing on so it is really important for us to know where you stand. Specifically:

# of features in development
# of features in testing
# of new features you plan to introduce before the 25th (preferably list those with a short description)
# estimated men-hours you will need to hit your milestone with a satisfactory product i.e. enough implemented set of features that can support the rest of the project.

Then also let us know about:
- items you planned but wont do
- resourcing issues: not enough working hands (and why?), not enough time, not enough info etc. 
- items the tutors can help you with. 

@sacdallago @goldbergtatyana @dmitry-n feel free to ask more question here as well.

**Comment by ghost** [comment]
We still need to find out, which information/resources are still missing and needed by other groups. (issues #85 and #60 are still a bit unclear)

These new features will be introduced if they are really needed:
- Centrality measure to estimate the importance of data. #103 
- #97 Multithreading
- Scraping missing information/ressources from wikia, hbo. (Which have to be defined first)

Further features are not planend, neither further have been issued by other groups.
To implement these features we still need volunteers. I can help @theocheslerean  out with scraping from other resources, but i am not able to do all of these features. 

Speaking of scrapers, we see that there are still quality issues and these have to be fixed until the final delivery. (Redirected wiki pages are not scraped for example)

**Comment by kordianbruck** [comment]
Also please check the Milestone filter - all issues are clearly assigned a milestone to be finished by.

**Comment by ghost** [comment]
Looks like everything remaining is implemented. Unfortunately @kordianbruck has not been updating the public server for the last two days. Also there seems to be a problem with the tokens to which @kordianbruck takes care of and so modifying api calls could not be tested. (Plod , @togiberlin )

Check:
https://github.com/Rostlab/JS16_ProjectA/milestones/v0.1.0%20Feature%20freeze

**Comment by sacdallago** [comment]
sooooo: close? :kissing_closed_eyes:

**Comment by kordianbruck** [comment]
Yes!
