### ISSUE TITLE
Remove any update methods from API

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#108]
following the discussion from https://github.com/Rostlab/JS16_ProjectE/issues/14#issuecomment-199318802

We should remove any API methods that manipulate the data that is scraped, so we maintain the ability to update the data set. 

@sacdallago correct?

**Comment by ghost** [comment]
I would just kick them from the routes...

**Comment by kordianbruck** [comment]
@Adiolis you forgot the add methods. I did that. This can be closed now.

**Comment by kordianbruck** [comment]
@Rostlab/js_cs_sose_2016_students there was one team, that actually was updating Data via the API - which team was this and what endpoint was it?

**Comment by ghost** [comment]
@kordianbruck @sacdallago I did not remove the add methods on purpose.
I don´t see them in conflict with our scrapers, because added data will not be scraped (yet).

**Comment by kordianbruck** [comment]
The question is if we actually want data to be added over the API. As far as I can read between the lines in the issue from project E, all data should be added via scrapers or automated methods so the API is actually reuseable.

**Comment by sacdallago** [comment]
@kordianbruck is right @adiolis . if updates are not allowed so shouldn't inserts, they should still happen over wiki, at least for the scraped data

**Comment by kordianbruck** [comment]
@Adiolis what about documentation? that will still remain in the docs...

**Comment by ghost** [comment]
Unfortunately you cannot comment comments out :P 
Probably just delete them and in later parts the comments can be reclaimed from git history or just done again, which is not a big act.
