### ISSUE TITLE
Plod stuff very buggy

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#113]
Heyho,

i don´t know who worked on controllers/characterPlod and so on.
It is very buggy and i had to remove it from the routes, because nothing is working (syntax errors and so on).
Also i had to remove the field in the character model, because it is required and not yet filled to the db. So every update on the characters collection gives me an error, because i have no plod to set.

Please fix this.

Also, please, check travis.

**Comment by ghost** [comment]
I fixed some problems, but i am not aware what this all is doing. So please check on it.

**Comment by sacdallago** [comment]
Which are the incriminated files? You can easily find the author by looking at the revision history :) But yes, thanks for noticing!

Hasn't @togiberlin worked on this?
