### ISSUE TITLE
Episodes dates: precision?

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectA#116]
The episodes' air dates currently contains a value like `2011-04-17T04:00:00.000Z`.

1) Does the time actually contain any information? I have my doubts that it aired at 4am. Like Prof. Rost said: Don't give precision you can't validate.
2) Are those values UTC or local time (DE) ?
3) The run time would also be interesting.

**Comment by ghost** [comment]
The reason, why a time is stored, is that there is no Date format without time in MongoDB:
https://docs.mongodb.org/manual/reference/bson-types/

One possibility now would be to store the date in string format like yyyy-mm-dd. @sacdallago 
Or just to ignore the time stored. 

I prefer the first, because search queries to the db would be easier. Especially all time indications would otherwise required to be 00:00:00 to be easier to query (no regex necessary).

**Comment by sacdallago** [comment]
1. `Z` [indicates the time zone](http://stackoverflow.com/questions/16151383/what-does-the-000z-of-yyyy-mm-ddt000000-000z-mean)
2. @Adiolis there are SO, MANY formats for time already. Let's not make up another one. Let's stick to storing a type in the db that is not a string representing a date, but rather a date representing a date :D Simply putting somewhere that precision is up to the day will be enough ;)
   Also: if you send a date to the API, you can simply `find` on the collection using an interval of +/- x days, which is even fancier than a string regex. _just saying_

**Comment by julienschmidt** [comment]
> Z is zulu (UTC) 

Why didn't I think of that :laughing: 

I'm fine with the current format, just document it properly. We were wondering how specific it is (you know.. we could display that in our timeline :wink: )

**Comment by ghost** [comment]
I will add that information to the apidocs :wink: 
No matter how obv. it is, that the time is not right :stuck_out_tongue_closed_eyes:

**Comment by ghost** [comment]
@kordianbruck update the api docs
@togiberlin i am a bit unsure about the Date types in the schemas of CharactersPlod and CharactersSentiments. Do they store a valid time? Otherwise please document in the according controller that the time has to be ignored.

**Comment by julienschmidt** [comment]
If it was local time, 4am would be a sensible value :wink: 

Edit: UTC _is_ almost local time

**Comment by kordianbruck** [comment]
Docs updated :)
