### ISSUE TITLE
Character Path data

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#117]
outsourced from #85
- [x] Table like the other PLOD or sentiment tables with character paths. (path is JSON data)
- [x] searchable like @Adiolis did it with the character location API
- [x] path data is provided by our group in a JSON file https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/data/paths.js
- [x] Connect it to hasPath attribute in character table => Each character with path needs hasPath == true https://github.com/Rostlab/JS16_ProjectC_Group10/issues/147

**Comment by ghost** [comment]
Okay, that is the last thing i will implement, guys, because i have done sth. similar before.
I´ve already invested tons of my lifetime for all of this :stuck_out_tongue_closed_eyes:

**Comment by ghost** [comment]
@mbandle Is it easy for you to change the file structure to a json format like: data/regions.json ?
Would be more consistent and easier for me to handle ;)

**Comment by bandle** [comment]
When you need any additional information from our group, just comment. 
Thank you :+1:

**Comment by bandle** [comment]
I`ll change it and tell you when its ready.

**Comment by bandle** [comment]
https://github.com/Rostlab/JS16_ProjectC_Group10/blob/db/data/paths.js

At the moment the changed version is only in our db branch - ill add it to the main branch when integration is ready if this works for you

**Comment by ghost** [comment]
@mbandle 
So is a db "table" charactersPaths like:
- _id
- name (for the character): String
- path: Array
- alive: Boolean

sufficient?

Which api calls are required? I am a bit unsure what find operations can be handled by the path field.

A hasPath attribute in the characters "table" will then indicate, that there are entries in charactersPath for that character. Can it be, that you have paths to an character, which is not provided by the wiki scraper?

**Comment by bandle** [comment]
@Adiolis 
The alive attribute is assigned to the path data. I don't know why you pulled it out of there? 
id, name and path should work.

We need calls to query a character name and get the path for the character. So this could work similar to what you did in the character-locations db.

Yes this is how hasPath was intended to work. 

It can but it should not be. We opened #105 when we encountered this problem.

**Comment by ghost** [comment]
@mbandle There is a character named Victorian Greyjoy in the json.
Probably you mean http://awoiaf.westeros.org/index.php/Victarion_Greyjoy ?

**Comment by bandle** [comment]
@AlexBeischl You did the paths? Who should this be?

**Comment by AlexBeischl** [comment]
@Adiolis Yeah, you are right, sry :/  swapped the a and o

**Comment by ghost** [comment]
Okay, i am done. 
Please use for updates  the data/characterPaths.json and don´t forget to request kordian to run `npm run update --collection=charactersPath` . 

@kordianbruck: Please run `npm run refill --collection=charactersPath` .
Also update the apidoc.

**Comment by ghost** [comment]
@AlexBeischl I fixed the typo in the data/characterPaths.json :wink:

**Comment by bandle** [comment]
Can you switch the name to regex or better add the slug option. Otherwise we have some problems in finding only one :)

This is our last thing to request :) I promise

**Comment by ghost** [comment]
For getByName there is the ?strict=true option. Is this sufficient?

**Comment by bandle** [comment]
:+1: works - didn't thought of that option - sorry

**Comment by kordianbruck** [comment]
Filling done :)
