### ISSUE TITLE
Region scraper: Scrap the regions´ wiki pages and not just portal with wrong names.

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#118]
- [x]  Scrap the regions´ wiki pages and not just the portal for the names, which are wrong, because of redirects.
- [x]  Tell kordian to update the collection

Otherwise we have problems like here #85 . Scraper gives The Iron Islands, but the name of the wiki page is actually Iron Islands.

**Comment by ghost** [comment]
@theocheslerean Just setting the redirects property in the bot params is not fixing the problem ;)
Because you fix the redirect to the portal, but not the links within the portal.

**Comment by kordianbruck** [comment]
Updated the regions in production.
