### ISSUE TITLE
Tear down server

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#119]
@kordianbruck Hello lover,  
since we are between FF and deadline **now** is the best moment to test how independent everything is. We should tear down your server and get **A** running on the rostlab machine! :) Any chance you want to assist me with that next week sometime?

**EDIT**: https://github.com/Rostlab/JS16_ProjectE/issues/19

**Comment by kordianbruck** [comment]
Sure, I can send you my public key to setup SSH Access to the machine 😘

**Comment by sacdallago** [comment]
:D that's all fine but can we physically meet?
No phun intended, this time.

**Comment by kordianbruck** [comment]
Our SSH sessions can physically connect on the server :heart:

**Comment by kordianbruck** [comment]
No, seriously, my or your place? :kissing_heart:

**Comment by sacdallago** [comment]
Where's your place? :D :D :D
I basically sleep at RostLab&trade;. We could meet there Wednesday late-mornin' 9:30/10

**Comment by kordianbruck** [comment]
@sacdallago let's do a hangout today!

**Comment by sacdallago** [comment]
Done.
