### ISSUE TITLE
G-B6: Add PLODs to characters

### ISSUE THREAD

**Issue by subburamr** [Rostlab/JS16_ProjectA#120]
Hi Team, 

You can get the PLODs for characters from our [repo](https://github.com/Rostlab/JS16_ProjectB_Group6). 
The values can be obtained from functions in the main.js file, please refer [here](https://github.com/Rostlab/JS16_ProjectB_Group6/wiki#mainjs-functions--usage) for usage.

Thanks,
Group 6

**Comment by sacdallago** [comment]
@kordianbruck where does this stand?

**Comment by mina-kleid** [comment]
Yea currently characters PLOD doesnt return anything

**Comment by sacdallago** [comment]
https://api.got.show/api/plod
