### ISSUE TITLE
Wrong Episode Airing Dates S01E10, S03E01, S04E04 & S04E05

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectA#123]
Dear Project A,

I've discovered a few wrong episode airing dates in our data, namely: S01E10, S03E01, S04E04 & S04E05.
The incorrect values are from the boxes on the episodes' own awoiaf pages [(like here)](http://awoiaf.westeros.org/index.php/Valar_Dohaeris_%28TV%29) while the right airing dates can be found on the awoiaf season pages (or on Wikipedia).

[AWOIAF Season 1 Episodes](http://awoiaf.westeros.org/index.php/Game_of_Thrones_-_Season_1)
- Episode 10: Correct date June 19 2011, current date June 12 2011

[AWOIAF Season 3 Episodes](http://awoiaf.westeros.org/index.php/Game_of_Thrones_-_Season_3)
- Episode 01: Correct date March 31, 2013, current date March 31 2012

[AWOIAF Season 4 Episodes](http://awoiaf.westeros.org/index.php/Game_of_Thrones_-_Season_4)
- Episode 04: Correct date April 27 2014, current date April 20 2014
- Eiposde 05: Correct date May 4 2014, current date April 20 2014

Looking forward to your reply!

Marcus

**Comment by kordianbruck** [comment]
@togiberlin can you share your Wiki login with me or correct the dates yourself?

@Adiolis when updating, are dates also corrected if they are updated on the Wiki?

**Comment by togiberlin** [comment]
@kordianbruck As far as I can see, the wiki entries are correct and match the above description by @marcusnovotny . I think the fault is in the scraper.

[AWOIAF Season 1 Episodes](http://awoiaf.westeros.org/index.php/Game_of_Thrones_-_Season_1)
Episode 10: Correct date June 19 2011, current date in DB: June 12 2011 (wrong date picked from episode 9)

[AWOIAF Season 3 Episodes](http://awoiaf.westeros.org/index.php/Game_of_Thrones_-_Season_3)
Episode 01: Correct date March 31, 2013, current date in DB: March 31 2012 (wrong year picked from description)

[AWOIAF Season 4 Episodes](http://awoiaf.westeros.org/index.php/Game_of_Thrones_-_Season_4)
Episode 04: Correct date April 27 2014, current date in DB: April 20 2014 (wrong date picked from episode 3)
Eiposde 05: Correct date May 4 2014, current date in DB: April 20 2014 (wrong date picked from episode 3)

**Comment by kordianbruck** [comment]
@togiberlin right, sorry - the wiki is correct but the scraper/filler does not seem to parse them correctly.

**Comment by marcusnovotny** [comment]
No sorry. They are correct on the pages I linked to because I wanted to propose you crawl from them. They're incorrect on the episodes pages (one page per episode not per season, link in the first post "like here") where I guess you're crawling from currently. I didn't post all the wrong entries.

**Comment by marcusnovotny** [comment]
@togiberlin @kordianbruck 

These are the sites you're crawling the **wrong data** from I guess:
[S01E10](http://awoiaf.westeros.org/index.php/Fire_and_Blood_%28TV%29)
[S03E01](http://awoiaf.westeros.org/index.php/Valar_Dohaeris_%28TV%29)
[S04E04](http://awoiaf.westeros.org/index.php/Oathkeeper_%28TV%29)
[S04E05](http://awoiaf.westeros.org/index.php/First_of_His_Name)

The season pages I linked in my entry post hold the correct data, that's why I suggested you crawl from them. Or correct the values on the pages I mentioned in this post, whatever floats your goat :)

**Comment by ghost** [comment]
Yes, the wiki we are scraping from is wrong.
Due to our policy, the wiki is to update.

Ty, @marcusnovotny :+1:

**Comment by marcusnovotny** [comment]
Thanks for your quick support on both issues!

**Comment by sacdallago** [comment]
Notify me when I shall run the scrapers again. @togiberlin has access to the wiki :sunglasses:

**Comment by togiberlin** [comment]
@sacdallago @marcusnovotny @adiolis @kordianbruck I changed the wiki, should be correct now. You can run the scraper again.

### 

Check infobox on the right:
- [Season 1, Episode 10](http://awoiaf.westeros.org/index.php/Fire_and_Blood_%28TV%29)
- [Season 3, Episode 01](http://awoiaf.westeros.org/index.php/Valar_Dohaeris_%28TV%29)
- [Season 4, Episode 04](http://awoiaf.westeros.org/index.php/Oathkeeper_%28TV%29)
- [Season 5, Episode 05](http://awoiaf.westeros.org/index.php/First_of_His_Name)

**Comment by sacdallago** [comment]
Episodes scraped.
