### ISSUE TITLE
House fell hourse templeton and house farman in characters list

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectA#126]
the character list still contains house names. please clean.

**Comment by boriside** [comment]
@gyachdav I was on my way back to Munchen, now I will take a look.

**Comment by boriside** [comment]
@gyachdav @sacdallago I saw the wrong entries.. Should we provide "removeById" functionality in the api?

**Comment by gyachdav** [comment]
can you investigate how they ended up as characters in the first place? Would be great if we can correct the scraper and refill the db with a corrected list.

**Comment by boriside** [comment]
yes, I already work on it.

**Comment by sacdallago** [comment]
Good. I don't think that removing items would do any good, as the policy of refilling would later put them in again. As @gyachdav suggested, it's better to solve the problem at the root, that is: the wiki. I know it's a big effort, but let's be consistent and let's hope the wiki gets better and better.

**Comment by ghost** [comment]
What needs to be inspected is the getAllNames function of the characters scraper. This is later used to determine the wiki pages to scrape. There seems to be picked up too much. I am not sure, if i have time do this, because of death in my girlfriend´s family. 

@theocheslerean

**Comment by boriside** [comment]
@Adiolis I do it right now.

**Comment by ghost** [comment]
@boriside The problem is that the scraper is buggy as f**ck. Some characters are even not scraped...
Many properties not scraped at all.

**Comment by sacdallago** [comment]
@Adiolis I'm sorry to hear about the loss :disappointed: I hope you and your girlfriend are keeping up.

Let some other people take some of your workload, @boriside thanks for doing that already. I'm also talking about the "page rank" issue.

**Comment by boriside** [comment]
@Adiolis It's not because the scrapper, but because the inconsistent information in the wiki. SO I think the best approach would be to exclude the exceptions. I also sorry about the loss, take your time. :(

**Comment by ghost** [comment]
Thank you both. It happend two days ago =/.
I am taking my time but this is just a quick fix of 5 minutes...
Feel free to edit my solution, whatever.

The scraper was taking all links instead only the first.

**Comment by sacdallago** [comment]
@boriside excluding data is a bold move :) I wouldn't do that, personally. Incorrect data is better than eventually no data. Wikis are a joint effort, thus mistakes are acceptable and encourage users to curate data.

@Adiolis should I run an update on characters?

**Comment by ghost** [comment]
I fixed the bug, that the scraping could not terminate because of the skipping of the houses.
Now, everything should be fine.

**Comment by sacdallago** [comment]
Thx
