### ISSUE TITLE
Images cannot be found

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#130]
After
1. Pulling the latest version of the code
2. [Refilling characters and updating their pageranks](https://github.com/Rostlab/JS16_ProjectF/issues/224#issuecomment-204715925)
3. [Updating the character paths](https://github.com/Rostlab/JS16_ProjectC_Group10/issues/219#issuecomment-204715476)

The images are not available anymore:
https://got-stats.herokuapp.com/characters/Rhaenys%20Targaryen

**Comment by ghost** [comment]
Refill collection characterImages

**Comment by sacdallago** [comment]
:D damn.

@Adiolis can you please tell someone to take care of updating the readme with a documentation that makes sense? Explaining also these dependency issues? And maybe put really all the refill commands there are?

> The collections are currently: ages, characters, cities, continents, cultures, episodes, events, houses, regions

**Comment by kordianbruck** [comment]
A simple look at the scripts tells you all options @sacdallago ;)

**Comment by sacdallago** [comment]
No.

A simple look at the readme tells me what I ought to do @kordianbruck I have no time to run through the scripts.

**Comment by kordianbruck** [comment]
```
var possibleRefillings = [
    'ages',
    'characters',
    'episodes',
    'cities',
    'continents',
    'cultures',
    'events',
    'houses',
    'regions',
    'characterLocations',
    'characterPaths',
    'characterImages'
]
```

**Comment by sacdallago** [comment]
This is not up to discussion :laughing: 
This needs to be in the readme or documented somewhere, you _need_ to have a clear documentation.. Com'on.

**Comment by kordianbruck** [comment]
Its not a discussion :tada:

**Comment by sacdallago** [comment]
Exactly. :D

**Comment by kordianbruck** [comment]
happy?

**Comment by sacdallago** [comment]
With you by my side, how could I not be? :heart:

**Comment by kordianbruck** [comment]
:kissing_heart:

**Comment by sacdallago** [comment]
No, no.. wait.. I don't get it.. Why I'm I assigned?
:joy:

**Comment by kordianbruck** [comment]
Update the characterImages collection plox

otherwise close it :)

**Comment by sacdallago** [comment]
Ahhh

[Who do you think you are talking to baybe?](https://got-stats.herokuapp.com/characters/Rhaenys%20Targaryen)

Just get me the documentation, then I'm happy.

**Comment by kordianbruck** [comment]
Its already in there ;D
