### ISSUE TITLE
How does the API handle special characters?

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectA#135]
How do I get info for Roland Crakehall (Kingsguard)?

I tried https://api.got.show/api/characters/Roland%20Crakehall%20(Kingsguard)

but getting
{"message":"Failure. No character with that data existing!","data":{"name":{"$regex":"Roland Crakehall (Kingsguard)","$options":"i"}}}

do i need to reformat somehow?

**Comment by boriside** [comment]
@gyachdav https://api.got.show/api/characters/Roland%20Crakehall%20 is the way to get the info for Roland Crakehall (Kingsguard). But this isn't correct since Roland Crakehall (Kingsguard) and Roland Crakehall (Lord) exist in the database. I change the label of the issue.

**Comment by sacdallago** [comment]
You could always use the `POST` request, but it's awful to use a `POST` for what is a `GET`

@boriside try expanding the `GET` functionality to also `GET` by slug, additionally to the char name and `_id`. I think that would solve the problem

**EDIT** and it should basically just mean to copy the function that gets by name, find on the slug instead of the name and add one line for the `GET` request to the router. 15 minutes work max

**Comment by sacdallago** [comment]
So where does this stand @boriside ?

**Comment by boriside** [comment]
@sacdallago I added the commit get by slug yesterday. It should be tested.

**Comment by sacdallago** [comment]
Can you test it and let us know?

**Comment by ghost** [comment]
Please test character names/slugs containing "(" or ")".
I see there a problem.

**Comment by boriside** [comment]
Should the server restart so the new things be integrated? If not I will test.  If problems I can work after 19:00 on it today. My other praktikum started.

**Comment by sacdallago** [comment]
I restarted the server when I told you to test. If you need me to pull yet another version and respawn just tell me

**Comment by togiberlin** [comment]
@gyachdav Correct would be `https://api.got.show/api/characters/Roland%20Crakehall%20%5C(Kingsguard%5C)`.
Before every `(` or `)` or `any other special char`, just insert `%5C`. This won't break the regular expression.
See also here: https://github.com/Rostlab/JS16_ProjectA/issues/111

**Comment by ghost** [comment]
Probably we should escape special chars automatically?
http://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex

**Comment by boriside** [comment]
Now bySlug works: https://api.got.show/api/characters/locations/bySlug/Eddard_Stark
@sacdallago please restart the server :)

**Comment by sacdallago** [comment]
Will do in ~20min

**EDIT** Done :heavy_check_mark:

**Comment by sacdallago** [comment]
Yeah but you removed the `GET` plod by slug and name, that's sort of a dick move :D

**Comment by sacdallago** [comment]
https://github.com/Rostlab/JS16_ProjectA/commit/07cb218d6336f0c3672a2019fb61d03acf249f50#diff-d640e5835a6b0c342cf705a06018c2b9L56

**Comment by sacdallago** [comment]
Thanks @togiberlin 
https://api.got.show/api/plod/bySlug/jon_snow

**Comment by sacdallago** [comment]
Now there's only another couple issues I noticed and opened :laughing:

**Comment by sacdallago** [comment]
This seems to be the winning solution:

https://github.com/Rostlab/JS16_ProjectA/issues/135#issuecomment-205371522
