### ISSUE TITLE
Character Plod IDs

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectA#136]
The character Plod iD is not the same as the character ID. therefore i cant ask for a specific character PLOD.
Maybe make an API for getting character Plod by name, since its the only consistent identification for characters we have

In this example you will find that the id of the character Plod is different from the id of the character
https://api.got.show/api/plod/byId/57017f23c5d04d80276b8739
https://api.got.show/api/characters/Viserys%20Plumm

**Comment by ghost** [comment]
Is using the characterSlug a solution?

Sorry for the inconvenience, but i am not aware of all the PLOD discussion. I am just helping out :yum:

**Comment by ghost** [comment]
I added an api call for /api/plod/bySlug/:slug . Is this sufficient?
@sacdallago: Please update the doc

**Comment by sacdallago** [comment]
Ok - will do

**Comment by mina-kleid** [comment]
@Adiolis Sorry for the late reply and thanks for adding it so fast.
Since the character name is the identification of the character we agreed upon. it will make life way easier for us to have an api for getting character plod by name (i.e plod/byName/:name) 

P.S. its a nice to have :smile:

**Comment by sacdallago** [comment]
I'll update the API and docs in about 20 min btw, currently not @ pc

**Comment by ghost** [comment]
Done. I am bit unsure, but i think that looking up characters with "()" in it, causes problems using the mongoose find method. That´s why the slugs have been introduced. 
Please test.

If it is not working, please, @sacdallago, assign someone else on the task.

**Comment by sacdallago** [comment]
https://api.got.show/api/plod/byName/edmure%20tully
seems to work

**Comment by sacdallago** [comment]
For the parenthesis problem there exists another issue opened by guy

**Comment by sacdallago** [comment]
https://github.com/Rostlab/JS16_ProjectA/issues/135#issuecomment-205205531
