### ISSUE TITLE
Fix find on PLODS per algorythm

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#137]
https://api.got.show/api/plod/byAlgorithm/gotarffplod
https://api.got.show/api/plod/byAlgorithm/gotplod

just return the first hit on find, while they should return the whole list of PLODS for that alg.

Please inform @togiberlin because I haven't seen him on here ever since we started with the PLOD problems and he is the main responsible for this.

**Comment by ghost** [comment]
@sacdallago I´ve notified him on facebook.

**Comment by ghost** [comment]
Just change
https://github.com/Rostlab/JS16_ProjectA/blob/master/app/stores/charactersPlod.js#L60

message[0] -> message.
Better remove the whole if clause since both cases are the same.

**Comment by sacdallago** [comment]
Yeah, probably the check should be `.length > 0` otherwise `404`, but this is implemented like shit.

**Comment by ghost** [comment]
The 404 check is in the controller. 
Unfortunately in the beginning some mistakes have been done (like error not being the first callback parameter, but success or somewhat), that are now spread all over. We would have needed the presentations in the beginning and one experienced member in NodeJs :anguished:

**Comment by sacdallago** [comment]
I agree.
I'll propose to change the way the seminar is hold with nex sem, there's a lot of space for improvement!

The thing that bothers me is mostly that @togiberlin disappeared. An -any- sign of life would have made a big difference in these days, especially considering that yesterday was the deadline and things **can** go wrong until the deadline

**Comment by togiberlin** [comment]
@sacdallago I already announced it, I have on 6th April an exam. I suggest this seminar to be a 10 ECTS Praktikum. Then there is upwards a lot more room

**Comment by togiberlin** [comment]
@sacdallago please pull newest version to server. Issue can be closed
