### ISSUE TITLE
Delegate functions return undefined instead boolean!?!

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#14]
Hello everyone,

i have no clue why the functions here: 
https://github.com/Rostlab/JS16_ProjectA/blob/master/app/stores/houses.js
always return undefined instead of a boolean.

One delegated call is for example here:
https://github.com/Rostlab/JS16_ProjectA/blob/master/app/controllers/house.js

Any ideas?

Stores are later useful for the scrapper part, that then have not to simulate a request to the controller to manipulate the database.

**Comment by ghost** [comment]
Okay, got it.
In nodeJs returns have to be implemented as callbacks. Will fix the code.

**Comment by sacdallago** [comment]
:+1: in JS to wait for a certain event, you would use Promises and .then() as explained: http://www.html5rocks.com/en/tutorials/es6/promises/?redirect_from_locale=de
