### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#140]
https://api.got.show/doc/#api-Characters-GetBySlug == https://api.got.show/doc/#api-Characters-GetByName

**Comment by ghost** [comment]
Didn´t he fixed it here:
https://github.com/Rostlab/JS16_ProjectA/commit/c2858b330b2fdbbce4f43653dad7160b0a66e494

**Comment by sacdallago** [comment]
He maybe forgot to tell me to update the documentation :dancer: can't really go through all his commits

**Comment by sacdallago** [comment]
But it doesn't work, anyway

**Comment by sacdallago** [comment]
P.S.: Thanks @Adiolis :)
