### ISSUE TITLE
URGENT -- update of wiki pages for new deaths

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#145]
Hi A guys,

after the first episode, two new people are dead. They were indeed likely to die according to our predictions, which is **GOOD** 🎊 

Now there are two points I'd like to cover, and I need help (I'm in the midst of setting up loadbalancers, caches, and other shit like that):
1. Is the Westeros wiki up to date? @togiberlin you have an account there
2. Can I refill the characters collection without breaking relations (sentiment --> char, plod --> char, img --> char)

For point two, if there is a particular sequence, eg: first refill char, then refill this, then that and so on, I would setup a new db and do all of this there, and then just swap out the db info in the config files.

I need hands on this and answers. If tomorrow someone can come at the office at RostLab and help me out with this, even better

**Comment by ghost** [comment]
I would recommend to always have a backup of the db, because the DOM of the awoiaf wiki can always change and the scraper could be not able to validate the data.
So it is a really good idea to use a new db and just switch to it as you suggested.

I am not aware of all dependencies of the scrapers, but i will look them up right now and write them into the README.

Unfortunately i am working the next days in a company and cant be at the Rostlab personally. =/

**Comment by sacdallago** [comment]
Ok! Thanks!

I would anyway always use the approach of having multiple node instances and then just swap out the config file with the latest version, backup the one before. I can setup virtually infinite parallel mongo instances

**Comment by ghost** [comment]
Okay, done.

I would start with cities and characters. Then characterImages. (All are somewhere prerequisites)
After them, everything as you wish.

**Comment by ghost** [comment]
@sacdallago 
Don´t forget to update the pageranks, too. See readme at the end.

**Comment by gyachdav** [comment]
whoa whoa easy there cowboy!!!!

@togiberlin **do not update the awoiaf wiki,** it follows the books not the show. 

Also no one update characters status before we decide what we do next! This is an editorial decision we have not talked about and should not be done so lightly.  Remember that our site follows the books, not the show.

If there was any action that was made here, it needs to be rolled back.

**Comment by togiberlin** [comment]
@gyachdav Ok!

**Comment by sacdallago** [comment]
@Adiolis thank you very much for the README update and the hints! I think I will start creating a new database soon and test it on my test API machines, then swap out the DNS entries.
So much work, so little time :D
