### ISSUE TITLE
Characters find requires token

### ISSUE THREAD

**Issue by krystian50** [Rostlab/JS16_ProjectA#148]
The endpoint: 
`https://api.got.show/api/characters/find`

and body:
`{ "male": true }`

returns 401 and: 
`{
    "message": "Need to send a token",
    "code": 401
}`

Is it correct?

**Comment by sacdallago** [comment]
It is correct.

POST requests are limited on the current instance. The calls exists, but are enabled by the API via tokens. If you wish to publish the API locally (or somewhere else), you can use calls other than GET.
