### ISSUE TITLE
Fixed syntax, mistakes and other

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#17]
When you are correcting some mistakes or the commas, link the commit to this issue, to be sure we have almost everything covered by the issues

**Comment by sacdallago** [comment]
If done, please close.

**Comment by theocheslerean** [comment]
No. This issue should not be closed until the end. Because there will be more syntax problems. This issue is just to have an overview of the corrections

**Comment by kordianbruck** [comment]
You can still reference the issue from commits, even when its closed. 

I will close it, so we get a better overview what actually still needs to be done.

**Comment by sacdallago** [comment]
:+1: @kordianbruck that's the way to go
