### ISSUE TITLE
Fix status codes

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#18]
Hello everyone,

First off: Nice work! We are liking the effort you have put so far!

Now a little remark on status codes [wiki](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), [W3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html):
- 200 is OK, which means the resource requested has been found and is returned in the body, usually
- 201 is CREATED, the resource was not there and has been created (so the successful addition of a house, for example, would return 201, not 200)
- 404 is NOT FOUND, thus the request has been sent and no server error has occurred (50x) 
- aso...

To list two examples where you might want to change this:
- https://github.com/Rostlab/JS16_ProjectA/blob/master/app/controllers/house.js#L20
- https://github.com/Rostlab/JS16_ProjectA/blob/master/app/controllers/house.js#L44

Correct codes are very important because they immediately give other developers a clear understanding of what is going on and if 3xx, 4xx or 5xx codes come up, what they might be doing wrong.

**Comment by ghost** [comment]
Ty =)
Will update them.

**Comment by sacdallago** [comment]
Can this be closed?

**Comment by kordianbruck** [comment]
Yes, I think we have proper codes in all the routes now.
