### ISSUE TITLE
API Documentation - use apidoc?

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#19]
We need to explain to the other teams what API endpoints we have and what purpose they serve. I would suggest to use apidoc (http://apidocjs.com/) for this purpose and use the inline commenting feature to provide a nice UI for the RESTful servicec
- [x] House
- [x] Episode
- [x] Character
- [ ] Scraper
- [x] Geography

**Comment by ghost** [comment]
I am working on the houses API doc ;)

**Comment by ghost** [comment]
I am not assigning myself to the whole task. Help is appreciated ;)

**Comment by kordianbruck** [comment]
I'll work some more on episodes

**Comment by ghost** [comment]
I finished the houses controller comments. Could you please take a look?
Most are examples since a more general description is not precise enough.

**Comment by ghost** [comment]
I am working on character and geography. 
Still scraper (and history?) left.

**Comment by kordianbruck** [comment]
Finished for now, till we know how to actually do the scraper. 

I'm not even sure we should need api docs for that, as the scraper should only be triggered manually via the console.
