### ISSUE TITLE
Populate DB - Add some data to be fetched

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#20]
- [x] mine Houses
- [x] mine Characters
- [x] mine Culture
- [x] mine History
- [x] mine TV episodes
- [x] mine Regions

**Comment by theocheslerean** [comment]
Create some scripts in the scripts directory to accomplish the task

**Comment by kordianbruck** [comment]
Is this not what the scraper should be doing?

Also how is this different to #12 ?

**Comment by sacdallago** [comment]
Agree. This or/and #12 have to go!

**Comment by kordianbruck** [comment]
@theocheslerean maybe you can even integrate them with grunt?

**Comment by ghost** [comment]
@kordianbruck @togiberlin @boriside @docjag 
Guys, we need you all to work.

**Comment by kordianbruck** [comment]
https://got-api.bruck.me/api/houses/ - works just great! Awesome!

**Comment by ghost** [comment]
i close this here, since #36 is rather used for this topic.

**Comment by gyachdav** [comment]
Nice job so far. seems like you have two Loras Tyrell's in your Characters data. you might want to open a new issue named data integrity.

**Comment by theocheslerean** [comment]
New issue #40  for uniqueness of every database entry
