### ISSUE TITLE
TypeError: Cannot read property 'ObjectId' of undefined

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#21]
Does anyone have an idea on this bug? Google yields no help...

> TypeError: Cannot read property 'ObjectId' of undefined
>     at Object.<anonymous> (/home/hansi/projects/tum/JS16_ProjectA/app/models/episode.js:8:36)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/hansi/projects/tum/JS16_ProjectA/app/stores/episode.js:1:77)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/hansi/projects/tum/JS16_ProjectA/app/controllers/episode.js:1:82)
>     at Module._compile (module.js:413:34)
> /home/hansi/projects/tum/JS16_ProjectA/node_modules/mongodb/lib/server.js:282
>       process.nextTick(function() { throw err; })
>                                     ^
> 
> TypeError: Cannot read property 'ObjectId' of undefined
>     at Object.<anonymous> (/home/hansi/projects/tum/JS16_ProjectA/app/models/episode.js:8:36)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/hansi/projects/tum/JS16_ProjectA/app/stores/episode.js:1:77)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/home/hansi/projects/tum/JS16_ProjectA/app/controllers/episode.js:1:82)
>     at Module._compile (module.js:413:34)

**Comment by sacdallago** [comment]
You seem to be trying to access the property of an object that doesn't exist or doesn't contain such property.

check the stack trace, that gives you plenty info, for example: look at
`JS16_ProjectA/app/controllers/episode.js:1:82`

Also, you can use `node debug app.js` and set some `debugger;` where you want to start debugging. Then use `n` to go on step by step execution or `c` to continue execution until the next `debugger;`.
https://spin.atomicobject.com/2015/09/25/debug-node-js/

**Comment by kordianbruck** [comment]
The problem is not with the controller but with the model: https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/episode.js

`Schema.types.ObjectId` is not defined by me but should come from mongoose, so not really something I can influence. Maybe I'm missing something but the error is not apparent to me... 

Plus: line 1 only has like 50 characters so the last line in the stacktrace about the controller makes double no sense.

**Comment by ghost** [comment]
I omitted in the models i touched the explicit _id definition. It is not really necessary. An (ugly) unique id string is automatically assigned to each db document.

**Comment by kordianbruck** [comment]
Great! So we don't need to add that instruction there explizitly. That was what I was thinking, but I thought maybe someone else already put some thought into it :tada: 

This issue was fixed by the typos in https://github.com/Rostlab/JS16_ProjectA/commit/0d9ecff3ab2dd3adce1f6625af272139f1976723
