### ISSUE TITLE
Copying no final artifacts

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#22]
Heyho everyone,

I´ve noticed that some of my controllers, stores for houses have been duplicated for episodes/characters. These house entities are not final yet (status code fixes, callback changes, some more api calls, renaming methods and so on). 

Thus, i would recommend to work step by step and have one api part fixed and then to do the copy, paste stuff. Editing it again and again and having inconsistencies is imo not very efficient. I actually really want to get the house api part final first and then reuse the code. For now i would remove the dups of the old code in the repo. 

Is that okay?

I don´t know how this is usually handled.

PS: It´s a bit strange, when making duplicates (even when the author himself makes duplicates) counts to the repo contribution stats defining the grade ;)

**Comment by ghost** [comment]
I got the episodes controller/store up to date. I actually did a lot of edits on the houses controller/store today ;)

**Comment by kordianbruck** [comment]
> PS: It´s a bit strange, when making duplicates (even when the author himself makes duplicates) counts to the repo contribution stats defining the grade ;)

Its not the number of commits or the lines you change - that would just be foolish to take that as a measurement. Its more if you were active throughout the project and contributed something everyday, no matter what. You could've C&P the code yourself ;D

Thanks for your great work though, much appreciated! Its a group effort :+1:

**Comment by sacdallago** [comment]
I assume this has been solved, I close the issue
