### ISSUE TITLE
Fixed schemas

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#23]
Inconsistencies in schemas

**Comment by ghost** [comment]
The schema needs further explanation.
What´s an event, age?

I don´t see that we are distinguishing between the books and tv episodes at all.

**Comment by boriside** [comment]
They all respond to "history":  In the timeline here: http://awoiaf.westeros.org/index.php/Timeline_of_major_events we have for example: Age of Heroes and in it Age of Heroes:,    The Long Night:, Building of the Wall: and The Night's King: events.

**Comment by boriside** [comment]
I will create comments and attach them now

**Comment by sacdallago** [comment]
This seems like a duplicate of #6
I close this, continue the discussion there
