### ISSUE TITLE
Stick to notation createdAt <-- created_at

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#24]
Hello everyone,

i´ve noticed that the notation is not consistent all over the app.
Please use the initial notation createdAt instead of created_at.

In other words: use camelCase instead of snake_case.

**Comment by sacdallago** [comment]
Has this been solved? If yes please close the issue

**Comment by kordianbruck** [comment]
I've searched for any occurrences, but there are none. So yes, this is fixed.
