### ISSUE TITLE
Controller/Store: History

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#26]

**Comment by ghost** [comment]
I am not sure, what the controller/store and its API will do.

**Comment by sacdallago** [comment]
Also needs to be closed today, #2

**Comment by kordianbruck** [comment]
@Adiolis according to #5 we should simply setup a timeline of the history listed on that page. Maybe with reference to characters and regions as a starter

**Comment by ghost** [comment]
@alschm  Are you still working on it? Please assign an issue to yourself if you start working. =)

**Comment by alschm** [comment]
sry, i think i've finished it a couple of minutes ago

**Comment by ghost** [comment]
Okay, i will do the finish. Close for now.
