### ISSUE TITLE
Controller/Store: Episodes

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#28]
Hi,

i got the controller, store, routes according episodes up to date. 
Still testing of the use cases is required. (API works as like the one of houses, but with route episodes instead houses)

Bye

**Comment by kordianbruck** [comment]
Is there some way of automating those tests? We can't test every API endpoint every time right?

**Comment by ghost** [comment]
For now everything is okay. Reopen if new issues occur.
