### ISSUE TITLE
Model Character

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#29]
i don´t think the property battles should be in this model.
Imagine a new occurring battle. First you have to add a new battle (with characters property!) and then edit every character occurring in it, instead of just defining them in the new battle entry.

What i also don´t like are the relationship properties like brothers.
This is bidirectional and therefore there is the possibility that the db is inconsistent.
Replacing the property by a new brothers model will otherwise extend the API and maintaining a lot of api calls is a bit exhausting. (more stores, controllers, routes)

What do you think?

https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/character.js

**Comment by sacdallago** [comment]
Needs to be solved today, #2

**Comment by kordianbruck** [comment]
I vote to remove battles altogether as it is not an requirement by the official project description.

Whats your suggestion otherwise in terms of modeling the relationship? I fear we don't have much of a choice here...

**Comment by ghost** [comment]
Normally further models should be introduced. One for parent, sibling and so on. This will lead than to an overkill of controllers/stores/API calls. 

But do we need this kind of information at all?

Other strange properties:
- episodes (n:m relation)
- placeOfX (reference to region/continent model?)
- event name (dateOfBirth makes this pretty clear)

**Comment by kordianbruck** [comment]
Again: we can comment it out for now and deal with it when someone needs it. I just commented out all the relationships that are too complex for our current situation.
- Episodes got removed
- placeOfX is that not the city? We don't have that modeled yet?
- eventName removed
