### ISSUE TITLE
Testing - Controller/Store: Characters

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#30]
I got the controller, store, routes according characters up to date. (They are just a "duplicate" of the houses stuff.)
Still revision, testing of the use cases is required. (API works as like the one of houses, but with route episodes instead houses)

**Comment by kordianbruck** [comment]
We can automate testing using nodeunit. Together with TravisCI #33 we would then get notifications for failed tests.

Check https://github.com/Rostlab/JS16_ProjectA/blob/master/test/default.js for an example test. 

I've opened up an issue in project E, as this is their task actually: https://github.com/Rostlab/JS16_ProjectE/issues/2

**Comment by ghost** [comment]
For now everything is okay. Reopen if new issues occur.
