### ISSUE TITLE
Fix dates in models

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#31]
Hey everyone,

the types for dates like 126 AC are inconsequently defined in the models.
I am not sure how detailed the dates have to be. (day, month, only years, or even only ages?)
If only the year is interesting, then i would just use a number.
Negative number for BC, positive for AC.
If we want to omit negative numbers, we can use a flag.
If more detailed information like the day is required, we can use additional properties/fields.

Alternative solution:
Define new type (how do we manage this with API calls?).

**Comment by gyachdav** [comment]
Only the year is interesting.

**Comment by sacdallago** [comment]
Needs to be decided today as part of the data model described in #6 / Other teams need to know how this data is gonna be represented

**Comment by ghost** [comment]
Since no one is really fighting about the best solution, i would say, we use type Number?

**Comment by kordianbruck** [comment]
Yes Integers / Numbers should be just fine. AC/BC with postive/negative numbers makes sense as well :+1:

**Comment by ghost** [comment]
I fixed it now. Close.
