### ISSUE TITLE
Public Server Infrastructure available now

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#32]
So apparently we are required to provide a public api that can be access by everyone and I didn't know about it. Discussion in issue #2 

I've quickly set it up on my own personal server here: http://got-api.bruck.me  (SSL is coming soonish)
Documentation for the API can be found here: http://got-api.bruck.me/doc/ (not complete, issue #19)

Suggestions welcomed!
@gyachdav @sacdallago is this sufficient?

**Comment by sacdallago** [comment]
Nice! Put http://got-api.bruck.me link in #2 PLS and a link to the routes (readme of this repo)

**Comment by ghost** [comment]
I´ve been already setting up wiki sites for this purpose with some further information just like the example login API.
https://github.com/Rostlab/JS16_ProjectA/wiki
For me this solutions is also okay, but can we enrich it with information about expected results?

**Comment by kordianbruck** [comment]
Now with https: https://got-api.bruck.me/api :star2: :dizzy: 

@Adiolis yes, I've mentioned in issue #19 we should use something more sophicticated than wiki pages for API documentation. And yes you can add expected results like success or errors - please check the docs for further information: http://apidocjs.com/#param-api-success-example

**Comment by ghost** [comment]
Well, fine for me.

**Comment by gyachdav** [comment]
Great! We will try to find a more permanent hosting solution for you later this week. Stay tuned. 

In the meantime, can we advertise this access point to the other students? When do you expect to have the data populated?

**Comment by ghost** [comment]
Theo and i are trying to populate the db today. So i suggest until tomorrow morning.

**Comment by kordianbruck** [comment]
@gyachdav it can stay on my server for the time of the seminar - no problems.

And yes, I've already added it to the Readme. Data will be in as soon as we have the scraper finished. I'm hoping today or tomorrow.

**Comment by kordianbruck** [comment]
I will close this issue as well for now.

Anything regarding the server, please let me know in a new issue.
