### ISSUE TITLE
TravisCI

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#33]
@sacdallago @gyachdav 

can we get TravisCI activated for this repository so we can use jslint and other automated testing tools for better code quality? 

For that please go to https://travis-ci.org and log in using an account that has admin rights to this repo.

I can also do it, if I get assigned admin access to this repository.

**Comment by gyachdav** [comment]
Loop in Project E, this is under their responsibility. here is the thread where they started discussing CI

https://groups.google.com/forum/#!topic/javascript-technology-2016/PjCceqwfwJw

**Comment by kordianbruck** [comment]
I know, but it would save us headaches when people push broken code right now. I can quickly configure a basic setup in a couple minutes, I just need someone to activate the integration :grinning:

**Comment by kordianbruck** [comment]
Added all configuration in: https://github.com/Rostlab/JS16_ProjectA/commit/b5cd87123f1a40d2d8e55f66e8be1763aff3fa23

Current status can be view at: https://travis-ci.org/kordianbruck/JS16_ProjectA

I need to push to my fork currently till it rebuilds. When the tutors/admins finally activate it for this main repo then it should work immediately.

**Comment by sacdallago** [comment]
@kordianbruck Done, but PLEASE, PLEASE let the members of E take care of this. This is out of the scope of your project!!!!!!!!

**Comment by kordianbruck** [comment]
@sacdallago thanks!
