### ISSUE TITLE
Still model issues to fix

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#34]
I am reviewing models and noticed following problems:
- Battle: I don´t get the event property there. I don´t see any event description in the wiki sites (for example: [Battle of Ashford](http://awoiaf.westeros.org/index.php/Battle_of_Ashford).
- Character: See Issue #29 
- House: Property "founded" could maybe just reference ages. Not sure how detailed this is known.

In almost all schemas:
We are modeling the relationships between models in a pretty ugly way.
For example: Region gets property houses and House gets a region property. 
Usually for 1:n relations, the houses property in Region should be omitted. Otherwise every edit, add, remove needs to touch both models and inconsistencies can be easily introduced. 
=> You get some information about one property from that model, but some only in another model.

For m:n relations a new model is usually created.

WE NEED TO FIX THIS NOW (YESTERDAY ;) ).
If i get no response, i will do it by myself, but please do not complain later. ;)

**Comment by kordianbruck** [comment]
- House / founded: just leave it in there for now. If we have the info some where we might add it. Otherwise we can still remove it later.
- I've removed the houses property in region - that really makes no sense.
- Battle: we are not required to do this at all. At least it is not meantioned in #5

**Comment by ghost** [comment]
I don´t know whose idea the battles model was, but i think the reason for it are the characters and charactersDied properties. For me it nonetheless is not supporting the other "Who dies next" project and so can be removed. (I actually don´t know how our db will support them anyway)

There are still some strange relations between models.
Skill <-> Characters
Characters <-> Episodes
...

**Comment by gyachdav** [comment]
Keep in mind that the "who dies next" may actually post an issue requesting this feature. By definition your project /is/ supporting everyone else:

Description: In this project we will lay the foundations for our system by integrating data from multiple sources into a central database. The database will serve the apps and the visualization tool that will be developed in other projects.
https://rostlab.org/owiki/index.php/Javascript_technology_2016#Project_A

**Comment by kordianbruck** [comment]
I would as with other issues not make battles part of version one. If another project needs something changed, they are welcomed to submit an issue. I would like us to focus on the things mentioned in #5 - which battles is not part of. Commented it out for now...

Others:
- Skills clearly are something that needs to be stored with a character
- I changed it to episodes having characters. Usually thats the way we want to see things: who was in that episode.
