### ISSUE TITLE
Stores´ getById(), getByName() return array

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#35]
Hi,

i discovered following bug.
The methods getById/getByName of all stores callback an array and not just the one json object.
Since ids and for example house names are unique, it is strange that the return type is an array.

```
    getByName: function(name, callback) {
        this.get({'name':name},callback);
    }
```

I don´t know how to fix this quickly since it is delegating the callback to the more general get method, that is required to return an array, and something like 

```
        this.get({'name':name},callback[0]);
```

is not working either. 

This bug is spread all over the stores.

**Comment by sacdallago** [comment]
Who wrote this code? Can that person be assigned as assignee? Thx @Adiolis

**Comment by ghost** [comment]
I fixed it =)
