### ISSUE TITLE
api queries

### ISSUE THREAD

**Issue by alschm** [Rostlab/JS16_ProjectA#37]
e.g.
- [x] getEpisodesByCharacter
- [x] getCharactersByHouse
- [x] getCharactersByCulture
- [x] getRegionsByContinent
- [x] getRegionsByCulture
- [x] getCharactersByGender

**Comment by alschm** [comment]
- [ ] getRegionsByContinent

**Comment by ghost** [comment]
We should rename the methods.
You get not just a single db entry, but multiples.
So, getEpisode**s**ByCharacter and so on.

E: I fixed it.

**Comment by ghost** [comment]
I would delay now the implementation of the remaining methods until we have sample data on which we can test.

**Comment by sacdallago** [comment]
Wonderful
