### ISSUE TITLE
MySQL instance available within Eduroam/LRZ network

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#38]
Thanks to @T1mK we have a local instance of MySQL running for you to fetch the data from instead of the wiki. you will need to connect to the following from within the 131.159.0.0/16 network:

`mysql -u westeros-ro -h 131.159.28.95 -P 22228 -p`

or

```
IP: 131.159.28.95
Port: 22228
User: westeros-ro
Pass: <see me for password>
Database: westeros
```

For the password please address me directly with some place I can send you the password **privately**.

Thanks and thanks to @T1mK

**Comment by boriside** [comment]
@sacdallago hi, would you create a password for me?

**Comment by sacdallago** [comment]
Where can I reach you :P privately? Sorry for answering this late..

P.S.: tomorrow I'm gonna sleep in, but as soon as I wake up if I have your contact I will forward the info!

**Comment by boriside** [comment]
@sacdallago  my email is boriside@gmail.com

**Comment by sacdallago** [comment]
@boriside done! Also, nice: you have a face :) :) :)

**Comment by ghost** [comment]
I think, everyone got notice of that and so this can be closed.
I
