### ISSUE TITLE
Data integrity

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#40]
Make sure that database entries are unique

**Comment by AlexBeischl** [comment]
Is there a check for duplicates? We would really appreciate it ;)

**Comment by kordianbruck** [comment]
Nope, not yet.

**Comment by ghost** [comment]
Now, mongoose will send back an error if names are duplicated. 
When filling the db i get no dups anymore.

**Comment by sacdallago** [comment]
`unique` is exactly the attribute I expected to find in the code to close this issue! Well done.
