### ISSUE TITLE
Geographic Data

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#41]
For our Project C (Group 10) we need Coordinate Data for cities, similar to LatLng.
We already started developing a small editor to assign Geo Data to given city lists.

Is there an API to get the Data in your Database? (I haven't found a city list and coordinate option yet)

To implement:
- [x] Routes
- [x] Model
- [x] Controllers
- [x] Stores

**Comment by ghost** [comment]
No, there is no city entity yet, but we can implement that ;)

**Comment by bandle** [comment]
That would be nice :+1: 
We need 
  name <-- City Name
  coordX <-- Place on Map: float [-180,180]
  coordY <-- Place on Map: float [-90,50]
  type <-- Which map symbol: enum [City, Town, Castle, Ruin, Others]
  prio <-- How important (which zoom level is the first to display it): int [0,6]

Additionally a field for the wiki link would be nice to

**Comment by sacdallago** [comment]
@mbandle I only add: prio --> priority
Sells away immediately what the field stands for / coding standards
:dancer:

**Comment by bandle** [comment]
Would it be possible to add a field to the regions table containing a polygon like:
[[x0,y0],[x1,y1], ...]

We would use it to draw polygons on the map to highlight regions

**Comment by togiberlin** [comment]
@mbandle: is x/y a string or number?

**Comment by bandle** [comment]
Its a coordinate (float) like coordX or CoordY with the same data range

**Comment by togiberlin** [comment]
@mbandle Mongoose can't store floats, only integers. Therefore I store it as a string and you can convert it

**Comment by bandle** [comment]
Ok 
you also can implement the whole field as string and we put the coordinates in a geoJson like format in.

Is there a max length for a string

**Comment by togiberlin** [comment]
@ mbandle Unless I haven't specified an upper limit, I guess no

**Comment by bandle** [comment]
I tried using the cities DB but it doesn't load. All other (ages, regions, ...) do. 

Do you have an idea?
https://got-api.bruck.me/api/cities/

**Comment by ghost** [comment]
The reason is, it is just not implemented yet.

**Comment by bandle** [comment]
Ok  Can you send me a message when its ready?

**Comment by ghost** [comment]
@mbandle 
Sure =)

**Comment by togiberlin** [comment]
@mbandle: Implemented
- [x] Routes
- [x] Model
- [x] Controllers
- [x] Stores
  Did i forget anything?

**Comment by ghost** [comment]
@togiberlin 
=)
Please assign the task to yourself before implementing ;)

Not sure if we also have to scrap the data from the wiki and populate the db with it... Or will the data be provided by the other group?

**Comment by bandle** [comment]
At the moment all the data is stored here:
https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/data/mapData.js

Line 10 is longer than it seems :)

**Comment by togiberlin** [comment]
@mbandle here is the cities model: https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/cities.js
I added more fields than requested (e.g. continent, cultures, events). Is it necessary?

**Comment by bandle** [comment]
We don't need the extra fields right now, but maybe in the future. We can talk tomorrow at the meeting if you are there

**Comment by togiberlin** [comment]
@mbandle I won't be there but my team member Kordian and also Boris Idesman.

**Comment by kordianbruck** [comment]
@togiberlin I've deployed the code, do I need to call a filler, so the data becomes available?
