### ISSUE TITLE
Episodes data unusuable 

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectA#43]
Not only is the list of episodes provided by the API very incomplete, it also offers just the air date and the title plus the episode number within the season in most cases. Moreover there are currently 7 entries at the beginning which contain no usable information at all.

For every episode aired so far, there should be an entry with the following minimal data:
- [x] Season Nr.
- [x] Episode Nr. (in Season)
- [x] Overall Nr. (unique)
- [x] Title
- [x] Air date

If the wiki does not provide this data, you should use other external resources, like IMDB or Wikipedia, but you should make sure that there is an entry for every episode aired so far (otherwise you can also not calculate the predecessor / successor reliable in #42).

**Comment by ghost** [comment]
Still several db collections are not implemented yet. I think, i finalized only the characters to the degree it has been planed.

**Comment by julienschmidt** [comment]
Thanks for the quick fix :+1: 
@kordianbruck please let us know when the server is updated

**Comment by sacdallago** [comment]
@kordianbruck why don't you set up a CRON job on your server to auto-pull the git repo and restart the node server?
1. Setup the ssh key to pull from the repo without need of user/pass
2. Set forever in your package.json as a dependence
3. Se up CRONtab to something like:

```
*/15 * * * * cd /path/to/github/repo && /usr/bin/git pull origin develop && ./start.sh
```

where start.sh is something like:

```
#!/bin/sh

export PATH=$PATH:/usr/local/bin 

if [ $# -ne 1 ]; then
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
   DIR=$1
fi

echo running frm dir: $DIR
cd $DIR

$DIR/stop.sh

npm install

PORT=3000 MONGO="mongodb://user:pass@db:port/collection" ./node_modules/forever/bin/forever start app.js
```

and stop.sh:

```
#!/bin/sh

if [ $# -ne 1 ]; then
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
   DIR=$1
fi

cd $DIR

PROGRAM_DIR="$(dirname "$DIR")"
echo PROGRAM_DIR is $PROGRAM_DIR
PROGRAM="$(basename $DIR)"
echo PROGRAM is $PROGRAM

set -o nounset
pid=$(ps -ef | grep node | grep $PROGRAM | grep forever | awk '{print $2}')
VALUE=$pid
if [ -z ${VALUE} ]; then
   echo no forever process running
else
   kill $pid
   echo stopping forever pid=$pid
fi

pid=$(ps -ef | grep node | grep $PROGRAM | awk '{print $2}')
VALUE=$pid
if [ -z ${VALUE} ]; then
   echo no $PROGRAM process running
else
   kill $pid
   echo stopping $PROGRAM pid=$pid
fi
```

**Comment by kordianbruck** [comment]
@julienschmidt Server is updated.

@sacdallago I'm not gonna pull unchecked code onto my server - sorry. I have done it before, but only where I know who the contributors are: https://github.com/kordianbruck/AutoUpdate

**Comment by sacdallago** [comment]
@kordianbruck point taken! Also I forgot that here (in A) you don't implement the feature model so you are totally right!
Btw: PHP?!?! Man why not FORTRAN? :laughing:  :laughing:  :laughing:  :laughing:

**Comment by julienschmidt** [comment]
Thanks guys, unfortunately the data at https://got-api.bruck.me/api/episodes/ didn't change yet.
