### ISSUE TITLE
Add parameter specification to the API docs

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectA#44]
See swagger example: http://petstore.swagger.io/#!/pet/getPetById.

**Comment by kordianbruck** [comment]
I'm guessing @Adiolis assigned this to me to update the server files? Done.

**Comment by AlexMoroz** [comment]
No, there are no specification for parameters yet.

**Comment by kordianbruck** [comment]
@AlexMoroz I've added the parameter for the episode controller, czech this out: https://got-api.bruck.me/doc/#api-Episodes-RemoveEpisode

Is that what you need?

**Comment by AlexMoroz** [comment]
Yes, but it will be more useful for find requests)

**Comment by kordianbruck** [comment]
So you want all the parameters for the find operations? These are just all the fields that are in the model - I'm not sure if this is really a good idea as we would be replicating the whole model in each of the find operations. You think its necessary to make it more clear?

**Comment by AlexMoroz** [comment]
What do you mean by 

> replicating the whole model in each of the find operation

But now it's not clear how to use it at all.

**Comment by kordianbruck** [comment]
@AlexMoroz basically for the find operations you can simply use any field from the models (https://github.com/Rostlab/JS16_ProjectA/tree/master/app/models). For example for episodes you can use any of the fields in the schema to find the episode: https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/episode.js

If I add all the fields to the documentation, this would be like replicating the whole model in the docs. I can do it, but I don't think it would be that much of an advantage to have it in there...

**Comment by ghost** [comment]
Is it a solution to link the according model to the regarding api method in the doc? 
And there is always one example of usage, too.

I see no benefit in copying every property into the doc.

**Comment by AlexMoroz** [comment]
@sacdallago What do you think about this?

**Comment by sacdallago** [comment]
@Adiolis it's ok. Make this clear in the docu somewhere though. Put a link to the schema definitions / folder on github with mongoose

Ok @AlexMoroz ?

**Comment by AlexMoroz** [comment]
If it ok for you, it's ok for me also. But I prefer the table with parameters and their description.

**Comment by ghost** [comment]
I think this can be closed. For api fixes see #49.
With my new fixes, there will be links to the according model. ;)
