### ISSUE TITLE
Respect TravisCI builds: best practice

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#47]
Hey guys,

please always check if your current commit breaks the build with travis CI (https://travis-ci.org/Rostlab/JS16_ProjectA) and fix possible syntax problems. The hints given by jslint really make sense and should be respected by everyone!

I don't want to go through each file every time and fix those things, you guys should learn how to write good code!

Thanks

**Comment by kordianbruck** [comment]
@theocheslerean @togiberlin @boriside @alschm @docjag @Adiolis

**Comment by ghost** [comment]
Is there an IDE integration or can this only be checked after pushing it?

**Comment by kordianbruck** [comment]
You can always install grunt locally and run `grunt test`.

Check the README
