### ISSUE TITLE
How to add data to the DB

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectA#48]
Can you add some short instructions how we can add entries to the city-table, please?

**Comment by kordianbruck** [comment]
Did you check the Docs? 

https://got-api.bruck.me/doc/#api-City-addCity

**Comment by ghost** [comment]
I don´t know who made the api doc for addCity, but it makes no sense.

Check https://got-api.bruck.me/doc/#api-Episodes-AddEpisode for example. The api works pretty similar. Just POST an json with the data on the api url. 

I opened a new issue #49

**Comment by AlexBeischl** [comment]
I've looked through the whole documentation and I honestly have no clue how to remove data...

On Top of the documentation, can you please add a example for all the usecases (add, edit... , remove!). Our group knows how to add now, but I thing it would really help the other groups as well ;)

**Comment by ghost** [comment]
For removal check for example:
https://got-api.bruck.me/doc/#api-Houses-RemoveHouse
Replace :id in the api url https://got-api.bruck.me/api/houses/:id
with the id of the entry, that has to be removed. Just send a DELETE request to it.

The most api doc entries have Header examples already.
