### ISSUE TITLE
Fix api docs

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#49]
The api docs have to be reviewed.
For example https://got-api.bruck.me/doc/#api-City-addCity is wrong.
All docs to the collections should be similar to the api docs for houses.
https://got-api.bruck.me/doc/#api-Houses-AddHouse

**Comment by ghost** [comment]
I fixed all api docs.

I´ve seen that the city api has no model. Is this intended?
Therefore, i could not link a model in these doc sections and well, the api gives actually no hint how the data is looking like. ;)
Pretty ugly.

@kordianbruck please update the public server ;)

**Comment by kordianbruck** [comment]
Done.

**Comment by ghost** [comment]
@kordianbruck Please update ;)

**Comment by kordianbruck** [comment]
done
