### ISSUE TITLE
Data extraction

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#5]
Preliminary results only(just lists with names, but no further information)
- [x] Characters: http://awoiaf.westeros.org/index.php/Portal:Characters
- [ ] History: http://awoiaf.westeros.org/index.php/Timeline_of_major_events
- [ ] Culture: http://awoiaf.westeros.org/index.php/Portal:Culture
- [ ] Geography: http://awoiaf.westeros.org/index.php/Portal:Geography
- [x] Houses: http://awoiaf.westeros.org/index.php/Houses_of_Westeros
- [x] TV episodes: http://awoiaf.westeros.org/index.php/Game_of_Thrones, especially dates of TV episodes.

Possible result: http://jsfiddle.net/davidThomas/nujtymy6/3/embedded/result/

**Comment by theocheslerean** [comment]
the function getAllHouseDetails is the function that fetches information about every house and returns an array of houses

**Comment by ghost** [comment]
This is pretty much the same as #20. Close.
