### ISSUE TITLE
Search by name is case-sensitive and input must be the whole name

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#50]
When I'm searching by name, I have to enter the whole name in order to get the data.

For example when I'm searching for Jon Snow:
Whole Name:
https://got-api.bruck.me/api/characters/Jon%20Snow --> works

Whole name in lower case
https://got-api.bruck.me/api/characters/jon%20snow --> doesn't work
{"message":"Failure. No character with that data existing!","data":{"name":"jon snow"}}

Only first or surname
{"message":"Failure. No character with that data existing!","data":{"name":"Snow"}} --> Doesn't Work
{"message":"Failure. No character with that data existing!","data":{"name":"Jon"}} --> Doesn't Work

Is there a special trick, I missed to get it working. 

We need it to make autocompletion according to our goals:
"Easy user interface to add more characters-locations associations. Use autocomplete when entering a new character name to recreate its locations on the map."

**Comment by ghost** [comment]
I implemented it that way. 
But be aware, that the result is now an array of matching entries.
@kordianbruck needs to pull the new code on the public server.

**Comment by bandle** [comment]
:+1: Thanks

**Comment by kordianbruck** [comment]
Pulled onto the public api :white_check_mark:

**Comment by sacdallago** [comment]
Nice enhancement.. @mbandle Another way of avoiding sending directly the query to the api (thus it having to match exatly the name) is to load the full list of available names, cache them in the frontend side and use a regex search (also allowing search for splits of the string (surname, middle, whatever), lower case, aso). Then send the right formatted data to the API.

**Comment by bandle** [comment]
We're doing sth like you proposed already on our dummy data. Now we wanted to test which way is faster. 
Either downloading it all and searching through by the regex or querying the database whenever a new key is pressed. 
I'll continue on this issue tomorrow.

**Comment by kordianbruck** [comment]
Yea, please don't dos my server :P

**Comment by sacdallago** [comment]
Faster? Downloading all names when the page is loaded in BG and regex the shit out of it :laughing:

**Comment by bandle** [comment]
Yeah sounds good - i'm already too tired now :zzz: 
Ok when regexing it I only need the name and not all the other stuff in the DB. Is there a possibility getting only the name columns?
@kordianbruck
