### ISSUE TITLE
Search Cities by Prio

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectA#51]
We would like to search cities by priority and display all cities with <= prio dynamically.
Can you please add a possibility?

Example:
findCitiesPrio: 3
-> cities with prio 0,1,2,3

**Comment by ghost** [comment]
I am on it. Should be no problem.

**Comment by ghost** [comment]
I implemented this function.
Just use the find api and formulate queries like {"priority": "<=2"}
<,>, >=, >= work all.

@kordianbruck Please pull the code to the public server.

**Comment by AlexBeischl** [comment]
Thank you very much :+1:

**Comment by kordianbruck** [comment]
Pulled onto the public api :white_check_mark:

**Comment by AlexBeischl** [comment]
It works great! Could you maybe add an equals as well?

**Comment by ghost** [comment]
Equals is just the old behavior:
 {"priority": "2"}

**Comment by AlexBeischl** [comment]
Oh too simple :+1:
