### ISSUE TITLE
Ages API, scraper and db filler done. Range find query implemendet. FINAL

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#53]
Hello everyone,

the ages collection is finished. =)
I also implemented a range find. Example: {'startDate' = '<0'}

@kordianbruck Please pull the code, truncate and fill the public db.

**Comment by kordianbruck** [comment]
:checkered_flag: done!

**Comment by ghost** [comment]
@kordianbruck 
Don´t forget to start the filler ;)
https://got-api.bruck.me/api/ages

**Comment by gyachdav** [comment]
The pull and fill process should be automated.

**Comment by ghost** [comment]
@kordianbruck Any possibilities to do so on your server? 
I think, "only" pulling the github repo automated would be necessary. The api calls are working already.

**Comment by kordianbruck** [comment]
I'm not gonna pull unchecked code onto my server - sorry. But I actually wrote a lib for this a while back: https://github.com/kordianbruck/AutoUpdate

Concerning filling the DB: yes this task can be automated with a cron job, if we want that. Mostly the fillers only need to be called once though, so I'm not sure if this is really necessary.

**Comment by gyachdav** [comment]
https://got-api.bruck.me/api/ages still empty.

**Comment by kordianbruck** [comment]
@Adiolis I can see the json on the server, but the insertion seems to fail

**Comment by ghost** [comment]
@kordianbruck Well, i deleted the collection, cache file and filled again and it works. How can you see a json on the server? What is the output in the cache file, console?

Console:
Request incoming.
Ages collection removed
Request incoming.
Filling started.
Cache file outdated.
Scrapping from wiki. May take a while..
{ name: 'Dawn Age' }
{ name: 'Age of Heroes' }
{ name: 'Andal invasion' }
{ name: 'Age of Valyria' }
{ name: 'The Seven Kingdoms' }
{ name: 'Targaryen Dynasty' }
{ name: 'The Fall of the Dragons' }
{ name: 'King Robert\'s Reign' }
{ name: 'A Song of Ice and Fire' }
Writing results into cache file "/Applications/XAMPP/xamppfiles/htdocs/got/app/../wikiData/ages.json"..
Inserting into db..
SUCCESS: Age of Heroes
SUCCESS: Andal invasion
SUCCESS: Dawn Age
SUCCESS: The Seven Kingdoms
SUCCESS: Age of Valyria
SUCCESS: Targaryen Dynasty
SUCCESS: A Song of Ice and Fire
SUCCESS: The Fall of the Dragons
SUCCESS: King Robert's Reign
Filling done =).

**Comment by sacdallago** [comment]
> Filling done =).    

So this isssssssssss closseable? :dancer: And it's FINAL, final? Right? Right?
![funny-animal-gifs9](https://cloud.githubusercontent.com/assets/6240943/13606084/cf3da69e-e54a-11e5-9423-0280bebdea4a.gif)

**Comment by ghost** [comment]
@kordianbruck 
@sacdallago It still has to be filled on the public server :P

**Comment by kordianbruck** [comment]
@Adiolis json in the file: wikiData/ages.json

But nevermind, somehow the filler worked just now. So its done!

@sacdallago I feel threaten :fearful:
