### ISSUE TITLE
Duplicate character data

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#54]
#52 is still not fixed I get duplicate character entries:

And they have different IDs like before.

https://got-api.bruck.me/api/characters/Jon%20Snow

``` javascript
{
    "message": "Success",
    "data": [{
        "dateOfBirth": 283,
        "title": "Lord Commander of the Night's Watch",
        "name": "Jon Snow",
        "_id": "56d912fb1e3cd5e6474a2ae1",
        "__v": 0,
        "updatedAt": "2016-03-04T04:45:47.653Z",
        "createdAt": "2016-03-04T04:45:47.653Z",
        "skills": []
    }, {
        "dateOfBirth": 283,
        "title": "Lord Commander of the Night's Watch",
        "name": "Jon Snow",
        "_id": "56d913b51e3cd5e6474a32c4",
        "__v": 0,
        "updatedAt": "2016-03-04T04:48:53.970Z",
        "createdAt": "2016-03-04T04:48:53.970Z",
        "skills": []
    }]
}
```

But not all are doubled like Tyrion Lannister:

https://got-api.bruck.me/api/characters/Tyrion%20Lannister

``` javascript
{
    "message": "Success",
    "data": [{
        "dateOfBirth": 273,
        "title": "Hand of the King",
        "name": "Tyrion Lannister",
        "_id": "56d913b61e3cd5e6474a35b1",
        "skills": [],
        "__v": 0,
        "updatedAt": "2016-03-04T04:48:54.176Z",
        "createdAt": "2016-03-04T04:48:54.176Z"
    }]
}
```

**Comment by sacdallago** [comment]
But is this actually reflected on the DB? Once you put the `unique` constraint in mongoose it should take care of these things, the collection itself should not allow this. Are you still using mlab/mongolab?

**Comment by ghost** [comment]
Look at the createdAt property. These entries are created before the fix.
@kordianbruck needs to delete the collection and fill it again. #52

**Comment by bandle** [comment]
Looking at the createdAt time, you refilled the database.
But now everything is in the db twice. 

```
{
    "message": "Success",
    "data": [{
        "dateOfBirth": 283,
        "culture": "Northmen",
        "house": "House Stark",
        "title": "Lord Commander of the Night's Watch",
        "name": "Jon Snow",
        "_id": "56df0e56d14319b30f5e2f51",
        "__v": 0,
        "updatedAt": "2016-03-08T17:39:34.548Z",
        "createdAt": "2016-03-08T17:39:34.548Z"
    }, {
        "dateOfBirth": 283,
        "culture": "Northmen",
        "house": "House Stark",
        "title": "Lord Commander of the Night's Watch",
        "name": "Jon Snow",
        "_id": "56df12cad14319b30f5e3735",
        "__v": 0,
        "updatedAt": "2016-03-08T17:58:34.996Z",
        "createdAt": "2016-03-08T17:58:34.996Z"
    }]
}
```

**Comment by ghost** [comment]
@kordianbruck 
Looks like mongoose has to be some kind restarted and re-indexed.
http://stackoverflow.com/questions/5535610/mongoose-unique-index-not-working
Otherwise the uniqueness in the model is not minded.

Quick "fix" would be to delete the collection and fill it only once (you did that twice 17:39 & 17:58), but this no real solution, but at least no dups are filled.

**Comment by kordianbruck** [comment]
I've deleted the characters and recreated it. It looks like its working now...
