### ISSUE TITLE
Get airing date of a specific Episode

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectA#57]
Hey guys, is it possible to get the airing date of a specific episode with the criteria: season and episode nr.? I looked at the API documentation but can't figure out what a request for that should look like.

**Comment by ghost** [comment]
Pretty easy =)
Just use the find api:
POST to https://got-api.bruck.me/api/episodes/find
{"season": 1, "nr":6} for example.

I will update the filler for the database now and then @kordianbruck  will need to start it on the public server.
Please, don´t expect the final episodes data for the next 1-3 hours. ;)
I will notify you ;)

**Comment by ghost** [comment]
@kordianbruck Please pull the code, delete the collection and fill it again. ;)

**Comment by kordianbruck** [comment]
@adiolis 1-3 hours is totally realistic ;D

All done - I also deleted and refilled the episodes.

**Comment by sacdallago** [comment]
I love you guys. If I ever decide to open up some company I'm gonna hire you. Know that.

**Comment by kajo404** [comment]
Okay I am able to make a POST request now, but I am only having success with the season. Whenever I try to use the episode information i get an error.

Current code: 

```
var request = require('request');
var url = 'https://got-api.bruck.me/api/episodes/find';
var form =  {
    form: {
        season: '1'
    }
}
var answer = request.post(url,form, function(err, resp, body){
    console.log(body);
});
```

Putting episode in the form creates the following error: 
`{"message":"Error: Bad request. Usage of non existing schema property!","error":"episode"}
`
Is this on purpose? This way i only can get the information for the whole season and have to do the speration work after. That's not bad but I was just wondering if there is a simpler way ;)

**Comment by ghost** [comment]
I am not sure, i get what you are doing, but you use a property called "episode" and it is not existing in the schema. (See error) 

What you are looking for is just "nr". "nr" contains the episode number within a season.
I hope, this helps...

**Comment by kajo404** [comment]
Oh yeah right never mind, maybe I should I try to wake up before I start working this.
Thank you for your help!

**Comment by ghost** [comment]
You´re welcome ;)
