### ISSUE TITLE
Characters Primary Key

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectA#58]
As far as I know, you are using the ID as the Primary Key for characters, can you add a possibility to not change the ID of existing characters, when you are loading up all data again?
(So a continuous Primary Key?) We have to use this key for mapping our path/location-data to the characters and after each reuploading we have to adapt all characters again :/

**Comment by ghost** [comment]
_id is automatically set by Mongoose.
For characters we actually use a unique name property field. Probably this is a solution for you?

**Comment by kordianbruck** [comment]
Automatically set by **MongoDb** - Mongoose is just the Database driver/connector and does not handle this stuff.

**Comment by sacdallago** [comment]
@AlexBeischl complains there might be duplicate characters with the same name.. How about another combination for a key: name+house, name+firstBookAppeared.. No clue! Just throwing stuff at you...

**Comment by ghost** [comment]
@sacdallago 
Our model defines the property name to be unique. So no dups are possible anymore.
This has been earlier the case, because the filler has been started several times and no validation for name dups was implemented.

**Comment by sacdallago** [comment]
Heard @AlexBeischl ? :) Ya gotya key right there :boom:

**Comment by AlexBeischl** [comment]
Thank you, this really solves the problem, just one request:
Can you please add a primary key section to your documentation?
I think it really helps ;) 
Thanks
