### ISSUE TITLE
What time zone is the airDate in?

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectA#59]
Also the airDate returned for season 1 episode 1 is `2011-04-16T22:00:00.000Z` 
The day is off by one as it was aired April 17, 2011 . Or maybe it has to do with time zones I don't know

**Comment by ghost** [comment]
The scraper gets it right and the filler translates it right by:

```
if(z == 'airDate') { 
  var date = new Date(episode[z]);
  console.log(date);
  ...
}
```

I console.log()ed the dates.
Seems like a database problem.
@kordianbruck Any ideas?

**Comment by ghost** [comment]
Got it fixed. Just needed to append the correct timezone to the date.
Public database will be refilled soon, but first i want to fix another issue.

**Comment by ghost** [comment]
I also fixed now some dates from the wiki scraper that could not be translated.
Now all episodes will have the correct airDate =)

@kordianbruck Please pull the code, delete the collection and refill. Sorry :P

**Comment by kajo404** [comment]
2 final things :)
- Your date string is not compatible with the Javascript date constructor. It looses the time (hours,minutes,seconds,...) when creating an object with `var date = new Date(dateString);`
- I am still unsure about what timezone the date is in, as it is not contained in the date string. Is it ET as this seems to be standard for HBO?

This could also be fixed by supplying the date in a String formatted like this:

> Sun Apr 17 2011 00:00:00 GMT+0200 (CEST)

Thanks for your help :)

EDIT: I might be wrong here and the error could be on my end
EDIT2: The string is correct, error was on my end.

**Comment by sacdallago** [comment]
@kajo404 just for further reference: The `.000Z` at the end of the date string already sells away the timezone ;)

**Comment by ghost** [comment]
@kajo404 Well, the wiki does not provide the time to an episode ;)

**Comment by kajo404** [comment]
Thanks @sacdallago , that is why I made the edits :) . @Adiolis So is GoT aired on cable first or do they make it available for streaming at a certain point in time?

**Comment by kordianbruck** [comment]
Done! Updated the code and refilled the DB.

**Comment by ghost** [comment]
@kajo404 i do not really know how this is handled in the US. Sorry.
