### ISSUE TITLE
Visualize the schema of the database

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#6]
To give people an impression on how it is structured

**Comment by boriside** [comment]
I start work on this task

**Comment by sacdallago** [comment]
Needs to be closed today, report on #2

**Comment by kordianbruck** [comment]
The current visualization can be found here: https://github.com/Rostlab/JS16_ProjectA/blob/master/misc/schema_visualization/Database%20Model%20draft%202.png

@boriside can you update the schema once more with the changes from today?

**Comment by ghost** [comment]
But start after the model issues are closed ;)

**Comment by sacdallago** [comment]
Aaaand then also put the link on the famous #2 :dancer: I will never get tired of tangoing around

**Comment by boriside** [comment]
Yes I will do it. Sry I don't actually get all messages so I response with a delay. But I will do it :)

**Comment by kordianbruck** [comment]
@boriside we have finalized the schema currently. Please finish the overview.

@sacdallago you are great at it!

**Comment by boriside** [comment]
@kordianbruck I'm currently working on it.

**Comment by boriside** [comment]
@kordianbruck  how to annotate the required fields :)?

**Comment by kordianbruck** [comment]
In ERDs you use Bold font on required fields, as far as I can say...

**Comment by boriside** [comment]
and for the one to many references: lets say characters: [{type: Schema.Types.ObjectId, ref: 'Character'}]: should it be "characters: ref Character" or "characters: [ref Character]"

**Comment by kordianbruck** [comment]
Second option I would say...

**Comment by ghost** [comment]
I don´t get the example.
For 1:n usually the reference is on the model, that needs no array.
For example: House and Rooms. The room would get the reference and house not a list of rooms.

**Comment by boriside** [comment]
@Adiolis so you think I should leave it?

**Comment by ghost** [comment]
I will take a closer look on it.

**Comment by boriside** [comment]
@Adiolis thanks :)

**Comment by ghost** [comment]
@boriside In which model is this exactly?

**Comment by boriside** [comment]
@Adiolis what do you mean?

**Comment by sacdallago** [comment]
OMG @boriside @Adiolis change profile pics, it hurts my eyes :laughing:

**Comment by boriside** [comment]
Done :D now its much worse :D

**Comment by theocheslerean** [comment]
Change the line that models the entity-relationship of continent-city and region-city to the proper type of line. You have the different lines in "Entity Relation"

**Comment by sacdallago** [comment]
This is post-feature freeze. Just to stress this out again. Probably the last thing you want to do

**Comment by kordianbruck** [comment]
Let's change the milestone then...

**Comment by ghost** [comment]
I don´t see that there will be change in the models anymore. 
So, this task can be done and finished :smile:
