### ISSUE TITLE
Secure the API

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#62]
As noted by another student today at the presentation, adding a layer of security to access the API is not at all a bad idea.

You can "get very very inspired" by this _random_ code I found on... oh, my! My GitHub!
- https://github.com/sacdallago/pssh/blob/master/index.js#L160
- https://github.com/sacdallago/pssh/blob/master/controllers/routes.js
- https://github.com/sacdallago/pssh/blob/master/configuration.js.template#L12

**Comment by kordianbruck** [comment]
@sacdallago Your line `if(request.get('token') === null) {` in your routes.js does not work, as it is `undefined`. Better use `if(!request.get('token')) {`

Check my _better_ code in here: https://github.com/Rostlab/JS16_ProjectA/commit/1354a177f8594a3c2e90fcefaf9fb4ca65c95366 :dancer:

**Comment by sacdallago** [comment]
:D that's quite the slip, whops; thx! To tantle at windmills: that's one head and 2 days of code, never said it would be perfect fifififi
