### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectA#66]
> XMLHttpRequest cannot load https://got-api.bruck.me/api/characters/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Chrome returns this error when you try to get the characters.

Some info:
http://www.html5rocks.com/en/tutorials/cors/

**Comment by sacdallago** [comment]
Finally someone notices this :D well done

**Comment by kordianbruck** [comment]
@sacdallago apparently no one was actually using the API till now :stuck_out_tongue_closed_eyes: 

@AlexMoroz should be fixed, please confirm

**Comment by sacdallago** [comment]
Btw, this happens on C10 as well @AlexMoroz

**Comment by sacdallago** [comment]
P.S.: @mbandle :arrow_up:

**Comment by AlexMoroz** [comment]
It happened only in Chrome till now)
It works in C10. The problem was in server configuration.

**Comment by sacdallago** [comment]
Nice **_testing_** @AlexMoroz . Even in the middle of the seminar :P :P :P

**Comment by kordianbruck** [comment]
Server configuration is done in nodejs directly, so no one actually did it with express till now :)

**Comment by AlexMoroz** [comment]
@kordianbruck  API died =(

**Comment by sacdallago** [comment]
@AlexMoroz @kordianbruck @mbandle next question to be asked I want one of you to answer. Really. At least pretend you pay attention :dancer:

**Comment by kordianbruck** [comment]
@sacdallago but I already did everything he is talking about yesterday: https://github.com/Rostlab/JS16_ProjectA/commit/59ba69615e17614a97baafe1d75547b7d5d2b382 :cry:

**Comment by sacdallago** [comment]
@kordianbruck did you take that from my awful awful code? :D 
P.S.: HE SAID IT EARLIER! someone had not payed attention

**Comment by kordianbruck** [comment]
@sacdallago I wouldn't dream of it. 

Yea, seems like it - but the ppl in the back row obviously didn't hear it... :loud_sound:

**Comment by bandle** [comment]
Using the /find now yields a 401

I haven't changed anything in the code

![bildschirmfoto 2016-03-15 um 10 46 34](https://cloud.githubusercontent.com/assets/11232638/13773759/547417ee-ea9b-11e5-8c77-d326903edb79.png)

**Comment by kordianbruck** [comment]
@mbandle #63 #62 You need a token now to call these functions :lock:

**Comment by AlexMoroz** [comment]
But why you added it for find? There is no need in token for get requests.

**Comment by kordianbruck** [comment]
@AlexMoroz it is a `POST` request tho. We need to send a body with json, thats why it is a post instead of get.

write me a short mail, so I can send you the token. I've also fixed the docs.
