### ISSUE TITLE
Character's ages

### ISSUE THREAD

**Issue by k-angelo** [Rostlab/JS16_ProjectA#67]
There are a few Birth/Death dates that are in format 299300 -. etc. It is basically 2 years stuck to each other

Generally these are very few up to 10(?) and I think that can be fixed manually. This is important as it messes with of the metrics used.

 Also if possible we would like to request possibly more dates of birth /  death added ?

**Comment by sacdallago** [comment]
Team **A** manually is no option, you know that right? :D the problem just seems to be a range, can be easily fixed with the right checks

**Comment by k-angelo** [comment]
Of course it can be fixed manually. Whether team A wants to fix their scrapper, or do it manually since its a small set ( and easily filtered ) and not rerun the whole scrapper again or both, is up to them and also depends on their backlog priority.
In any case it is important for us, whether you prefer a quick fix or code update is up to you guys.

**Comment by ghost** [comment]
I´ve reimplemented the scraping of birth and death dates.
Bug should be fixed and i fetched 100 dates more than before.
