### ISSUE TITLE
REST API conventions

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectA#68]
According to rest api conventions POST request is used for:

> To insert (create) a new customer in the system, we might use:
> POST http://www.example.com/customers

So this is wrong:

> POST 
> https://got-api.bruck.me/api/ages/find
> POST
> https://got-api.bruck.me/api/characters/find
> etc..

**Comment by kordianbruck** [comment]
How to do it:
http://stackoverflow.com/questions/5020704/how-to-design-restful-search-filtering

Why not to use `GET`: 
http://stackoverflow.com/questions/978061/http-get-with-request-body?lq=1

**Comment by sacdallago** [comment]
@AlexMoroz is right, usually when you have a find operation on data, it translates to a `GET`. Url encoding is stil the thing you would do in this case (Yes, url-encoding!) but now it's too late to change this (too many people already depend on the api)

**Comment by AlexMoroz** [comment]
Just for info, you send body only here https://got-api.bruck.me/doc/#api-City-getCities .
