### ISSUE TITLE
Fetch characters for every episode

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#70]

**Comment by ghost** [comment]
So, we have for this still no solution. Don´t we?
Otherwise we propably need to scrap from that wiki:
http://de.gameofthrones.wikia.com/wiki/Der_K%C3%B6nigsweg_(Episode)

**Comment by yashha** [comment]
maybe from here?
http://www.imdb.com/title/tt0944947/epcast

**Comment by sacdallago** [comment]
Great suggestion @yashha . Some off-the-hook data ripping :D

**Comment by ghost** [comment]
Since this is very important, i have mercy and will do that today :P

**Comment by yashha** [comment]
It looks like most of the imdb pictures are copyright protected
http://www.imdb.com/media/rm2262031104/ch0155776
Should we get permission of hbo?
Wikia has done this: http://gameofthrones.wikia.com/wiki/File:Westeros_HBO.png

**Comment by ghost** [comment]
Imdb fetching is ready. Still the filling of the db and with this the matching of character names remains.
Result of the scraping: [data/cast](https://github.com/Rostlab/JS16_ProjectA/blob/master/data/cast.json)
I will separate cache files from mainly constant data files. (cast will not change very often :P )

**Comment by ghost** [comment]
Soooo. I did it. What a callback hell...
But it works very smooth and only characters like 'Whore', 'Stark Guard' could not be matched to the db since they do not exist for good reasons in the wiki.

Also the characters get updated by the actors. We have this information now for 161 characters. =)

@kordianbruck

**Comment by sacdallago** [comment]
That Whore
![](https://pbs.twimg.com/profile_images/2068778661/ba_dum_tss.png)

**Comment by marcusnovotny** [comment]
I stumbled upon this by accident, but all the actor data seems to be wrong. I've checked around 10 entries. I don't know if anyone is actively using this data, just thought I should let you know!

**Comment by togiberlin** [comment]
![f7cb741def2c550e274291ccd51abbf8](https://cloud.githubusercontent.com/assets/13764830/14185766/885389f4-f77b-11e5-8d2a-32b7b002ba62.jpg)
