### ISSUE TITLE
Character: new fields to be added

### ISSUE THREAD

**Issue by ThuyNganTran** [Rostlab/JS16_ProjectA#72]
- [x] Spouse 
- [x] Allegiance/affiliation (it's in the wiki infobox!)
- [x] Popularity of each character 
- [x] parents
- [x] ~~features according to the model for character would be great~~
- [x] book appearances
- [ ] add empty values for PLOD so we can add our data later
- [x] last visited place (place of death for dead characters)

**Comment by kordianbruck** [comment]
@ThuyNganTran is this a request for additional fields in the character? Yes?

**Comment by ThuyNganTran** [comment]
Yes, sorry I forgot to specifically mention that

**Comment by boriside** [comment]
features according to the model for character would be great - like what?

**Comment by kordianbruck** [comment]
@ThuyNganTran "features according to the model for character would be great" yea, that makes no sense to me either. Also: what data type should "PLOD" be? We need two of these values for each of the groups right?

**Comment by boriside** [comment]
@ThuyNganTran array of points?

**Comment by togiberlin** [comment]
@kordianbruck I would make PLOD as 2 digit Integer. As Prof. Rost mentioned, 4 digit accuracy after decimal point is pointless.

**Comment by boriside** [comment]
Well I think [point(x,y), point(u,v), ... ] is enougth

**Comment by ThuyNganTran** [comment]
What I wanted to point out is this model: https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/character.js 
Because at the point I created the issue, quite a few there mentioned attributes weren't in the character database. (I think age still isn't)

**Comment by kordianbruck** [comment]
@ThuyNganTran yes that is because we have added them already. Regarding age: it is not planned to have it as a field but rather we only save the birth and death date.

@boriside let's split this issue and talk about PLOD in another one as there are multiple groups involved in this. So this one is done for now.

**Comment by ThuyNganTran** [comment]
@kordianbruck What I was trying to say is that the database did not contain all attributes you wanted to implement according to your model at the time I created the issue and I'm not talking about the attributes you added under //issue #72.  Just tried to clarify the question concerning that point. And 'age' ist still not in the database. Also, a character pleads allegiance to a House or a a group (for example 'Night Watch' or 'Gold Cloaks'. Thanks for the quick wrap up of the issue.
