### ISSUE TITLE
Build is failing.

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#73]
Com'on guys, it takes like 0.3ms to check your code before pushing it.

**Comment by kordianbruck** [comment]
Its been failing for the last two weeks and I have already advised everyone, to please make sure committed code is fixed. I've went through all the files yesterday already in #64 - I'll merge it right away before people start modifying the code and I have to redo the fixes.

**Comment by kordianbruck** [comment]
@Adiolis maybe you got a minute and can make sure I didn't mess up somewhere. Thanks!

**Comment by sacdallago** [comment]
Build is failing again, please fix

**Comment by ghost** [comment]
@sacdallago  @kordianbruck 
I don´t get the jshint:
 277 |                var $ = HtmlParser.load(data.parse.text["*"]); 
                                                                      ^ This character may get silently deleted by one or more browsers.

It is pointing on " ; ".

**Comment by sacdallago** [comment]
First thing that comes to my mind is try to shout! So browsers don't "silently" delete it :D :D
No but srsly I don't quite know. @TheZoker suggestions?

**Comment by sacdallago** [comment]
also CC @gyachdav @dmitry-n

**Comment by TheZoker** [comment]
@Adiolis No it's pointing to the character at the end. You can't see it in Github, but if you run the grunt locally, you will see it in the consol. I fix it here: https://github.com/Rostlab/JS16_ProjectA/pull/131
