### ISSUE TITLE
Use mLab for storage

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#74]
Apparently knowing how the models (https://github.com/Rostlab/JS16_ProjectA/tree/master/app/models) look like is not enough, so we will move everything to a mLab instance, where everyone can dive into the collections.

I'd like to encourage everyone to think about what this means for latency and performance. We will have to tackle this maybe some day.

**Comment by sacdallago** [comment]
No. Not enough :D sacrifice latency for collaboration.
Hey, wasn't there a little someone today mentioning the tutor(s) should start enforcing collaboration? :D <3

**Comment by kordianbruck** [comment]
@sacdallago pssst, don't use my comment against me :yum: :hear_no_evil:

**Comment by kordianbruck** [comment]
@Rostlab/js_cs_sose_2016_students the API is now running on a mLab MongoDB. If you want to poke around the data, let me know and I can create a direct access user. You should still use the API for any requests. Of course this made it necessary to rerun all the fillers, so any data saved to the DB from before is gone. We now are storing a whooping 1.46 mega bytes of Game of Thrones data!
