### ISSUE TITLE
Add more statistics

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#77]
Main issue here: https://github.com/Rostlab/JS16_ProjectF/issues/169
- [ ] [Google Doc GOT Statistics](https://docs.google.com/document/d/17VFx2gogagzMGQy1BOFpffUVfvSo8fHejDl2pNKMfvA/edit?ts=5707bc94)

**Comment by kordianbruck** [comment]
I really have no idea how to calculate the age across the characters. Ideas welcome!

**Comment by gyachdav** [comment]
Just use the date you /do/ have.

**Comment by kordianbruck** [comment]
@gyachdav yea, the problem is that we have negative dates and calculating that in a aggregation function is kinda complex. So I'm currently thinking of doing a cron job that calculates the age once and then simply have the data pulled from the DB when the stats endpoint is called.

**Comment by togiberlin** [comment]
@kordianbruck As of beginning of the new season 6, we are at this date: 305 AC
With that information, we could calculate the actual age of characters
`BAC (Before Aegons Conquest of Westeros)`
`AC (After Aegons Conquest of Westeros)`

**Comment by kordianbruck** [comment]
@togiberlin well yes, but we have the birthDate and deathDate both of which are simple year numbers. Negative numbers are BAC and positive AC - Now I can't simply subtract the birthDate from the deathDate because of the negatives. That's the actual problem I don't know how to solve with a mongoose $aggregate query.

**Comment by gyachdav** [comment]
how about setting a rule

abs(birthDate)>abs(deathDate) ? birthDate = -birthDate

**Comment by kordianbruck** [comment]
```
Birthdate       Deathdate                abs(birthDate)>abs(deathDate)         age = deathDate - birthDate
      -                     -                   => true                                      = -deathDate + birthDate
      -                     +                  => depends                               => depends
      +                    -                   => no possible                          not possible
      +                    +                  => false                                     = deathDate - birthDate
```

Case 2 will still have to be handled individually. E.g.: born -30, death in 10. That would evaluate to true with the above rule but thus will calculate age -20

**Comment by sacdallago** [comment]
You guys never cease to amaze me :D We are gonna get so much traffic :P btw, you will never guess the coolest domain name ever we _got_ for this project ! :D :D :D :D

**Comment by togiberlin** [comment]
@kordianbruck nice overview. We should also keep in mind, that there is no year 0 in the real-world `before christ/BC` and `anno domini/AD` system. What about the GoT world? As I can see from here, they have a year 0 [The Targaryen Conquest - Timeline (search for keyword "0 AL")](http://gameofthrones.wikia.com/wiki/Timeline)

**Comment by kordianbruck** [comment]
Yea, thats another good point. It is just too complex to do in one go in a aggregation function I think. I will have to experiment more...

**Comment by togiberlin** [comment]
@kordianbruck [How to store negative Dates (BC) in JavaScript by using .toISOString() parsing method](http://scholarslab.org/research-and-development/parsing-bc-dates-with-javascript/)

**Comment by gyachdav** [comment]
More stats:
- [ ] num of bastards per realm. Tip: bastard last name is realm specific: sand is the last name for a natural born In Dorn, Rivers in the river lands and Snow in the north. Ref: http://awoiaf.westeros.org/index.php/Bastardy
- [ ] number cities per continent, realm

**Comment by gyachdav** [comment]
Apologies for the formatting issues I'm posting it all from my phone while on the plane back to NY :p

**Comment by gyachdav** [comment]
where does that stand? Have you communicated with F so they would show all your wonderful stats?

**Comment by gyachdav** [comment]
@kordianbruck feel free to reassign to one of the many devs you have at your disposal.

**Comment by gyachdav** [comment]
@togiberlin beautiful work https://github.com/Rostlab/JS16_ProjectA/blob/master/wikiData/statistics/CharacterStats.pdf
shame i found it by wandering around and that you haven't brought it out. 

Anyways this is exactly what i am looking for to be shown on the site. It would be best if we can show this in sections instead of showing a long page with all the stats. Think about a way that we can incorporate this material in a weekly blog following airing of each episode. 

Moving forward, can you please take the lead on that and coordinate with @jorjo1 @mammuth the move of this data to be presented using google charts or some other quick way to visualize the stats you collected?

@kordianbruck i'm reassigning this to @togiberlin

**Comment by gyachdav** [comment]
Status? @togiberlin we need your feedback here.

**Comment by togiberlin** [comment]
@gyachdav Actually what I did there was done manually with Numbers (Apple's Excel equivalent). I used a very early version of our scraped data. If you want an updated version, what are the requirements?
- Static (.jpeg / .png) or
- Dynamic? (Google Charts etc.)

I would prefer static.
For static, there are many [Photoshop dashboard templates](https://www.behance.net/gallery/14010225/PrasastiEnom-PSD-Dashboard-Webapp-Template)
[Infographic template example](https://www.behance.net/gallery/18985133/10-FREE-Infographic-Vector-Templates)
[Another example here, very hipster but takes a lot of time](http://www.socialmediatoday.com/content/blogconomy-blogging-stats-infographic)

Also: when is this needed? I'm writing exams on 31st / 1st and 6th.

**Comment by gyachdav** [comment]
We'll go with what you're most comfortable with. Just remember that the color scheme needs to be adapted to the color scheme and style used on the website. Please coordinate with @marcusnovotny about generating those info graphics. He will work on creating landing pages next week and will need your support. Would you be able to help next week?

**Comment by togiberlin** [comment]
@gyachdav I have 3 upcoming exams, I need to prepare for it. But I can dedicate an hour per day for the infographic. I would orientate the UI/UX on Project D. Supporting him...well, what I can do is give some advice here and there. @marcusnovotny How is the progress on the landing page? Have you started with a wireframe or UI design?

**Comment by gyachdav** [comment]
@togiberlin sounds good. glad to hear you're on board and good luck on those exams!

**Comment by marcusnovotny** [comment]
@togiberlin Hey there! We'll decide on number & topics of landing pages tomorrow. Then I'll write & collect the content, put it into .html files and send it to Group F, maybe along with a simple wireframe. The design will be handled by them. Some relevant statistics would make nice filler elements next to our actual tools on those pages. I'll get back to you tomorrow with more info, just to give an overview already. :)

**Comment by ghost** [comment]
Status? Is this really feature freeze?

**Comment by gyachdav** [comment]
changed to delivery

**Comment by togiberlin** [comment]
Here is the main thread: https://github.com/Rostlab/JS16_ProjectF/issues/169

**Comment by sacdallago** [comment]
Let's follow up on the main thread
