### ISSUE TITLE
List of most important/popular characters

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectA#78]
Is it possible to get a list of the characters that are currently interesting/popular ? We would like to run the sentiment analysis only for the characters of "value" I dont think there is a point in running them for all 2000+ names in the list ;)

**Comment by gyachdav** [comment]
As mentioned in class today there is an east way to check importance -- just count the number of inbound links to a page. One of the ML groups will implement a page rank algorithm but you can even go the basic route by using the data I already produced for all characters  - https://rostlab.org/~gyachdav/awoiaf/Data/pageRank/

You should really be interested in the score given in the first item of the list (the character's inbound links score). find a media score for all characters and the top half should be your important/popular ones.

**Comment by kajo404** [comment]
Thank you we will use that list and work with it

**Comment by sacdallago** [comment]
Actually; you can use [centrality](https://en.wikipedia.org/wiki/Centrality) measures with the data that you have. Would make very much sense.
Or build a centrality measure with the inbound, outbound links. There seems to be a [great package](https://www.npmjs.com/package/ngraph.centrality) for this out there

**Comment by kajo404** [comment]
Sorry I have to reopen the issue, I can't figure out how to even access the data here [https://rostlab.org/~gyachdav/awoiaf/Data/pageRank/](https://rostlab.org/~gyachdav/awoiaf/Data/pageRank/). 

I want to compare the entries on the website to my list of characters I get from Database A and then get the first score like Guy suggested. I have no idea how to get this data into my script.

**Comment by kordianbruck** [comment]
@gyachdav that data is not standard json is it? I can't seem to parse it.

@kajo404 I don't see how this has anything to do with Projects A scope - we can provide you with a data store, where you can save guy's analysis to but thats about it... Please check with the team from yesterday, that was talking about machine learning and the popularity. Alternatively you can check IMDB for the main characters of the show, but that would be manual work...

**Comment by kajo404** [comment]
@kordianbruck This was only initally about A because I thought you might already have such a statistic

**Comment by gyachdav** [comment]
download archived character data from https://rostlab.org/~gyachdav/awoiaf/Data/pageRank/allchars.tgz

**Comment by kordianbruck** [comment]
@kajo404 please continue in one of your projects issues then! :+1:
