### ISSUE TITLE
Redundant api methods like getCharactersByGender

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#79]
Hi,

is there a reason why there are for characters redundant api methods like:
https://got-api.bruck.me/doc/#api-Characters-GetCharactersByGender
This can easily be done with the find api. 

It is confusing, that for some properties there are such methods and for others not. Other models do not even have such methods at all. Only the ones that identify one single record make sense to me. 

Btw. the api docs to them are also faulty and the implementation of the methods, is even not working.

I would just remove all these redundant api methods.

**Comment by kordianbruck** [comment]
Yes, I agree. That one makes absolute no sense. Special get methods just make sense for single records to be returned.

**Comment by kordianbruck** [comment]
These routes were added by @alschm in #37 - I don't know why exactly these were needed, but it absolutely makes no sense to have those.

**Comment by kordianbruck** [comment]
@Adiolis I think that  should be all right? Closing this for now

**Comment by ghost** [comment]
@kordianbruck jep
