### ISSUE TITLE
Add a city filler

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#82]
We need to import the cities. The easiest would be to write a filler that takes a json and inserts all the entries into the collection.

**Comment by ghost** [comment]
Pretty much we just need to fill it with this:
https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/data/cities.js

I can do that ;)

**Comment by kordianbruck** [comment]
Yea, let's just add that to our wikiData/ folder and sync it using Git :+1: 

https://github.com/Rostlab/JS16_ProjectA/commit/8026eeec85e7cf7e2709fe61aafeabd29ab6f153

**Comment by ghost** [comment]
@kordianbruck 
Could you do the syncing? I have no idea, how this is managed...
I would also appreciate a short explanation or link =)

**Comment by kordianbruck** [comment]
@Adiolis you download the file -> save in the wikiData folder -> commit -> ??? -> Profit!

**Comment by ghost** [comment]
@kordianbruck 
But it is not automatically synced? Would be nice, if we are always up-to-date.

**Comment by kordianbruck** [comment]
@Adiolis let's ask projectC where that data materialized from. I don't think it will update too often, but you are right, we should automate a scraper for the cities.

**Comment by ghost** [comment]
@kordianbruck You can fill the db with the new filler.
Some validation errors occur, because there a dups in the json. No problem. Dups are then just ignored.

**Comment by kordianbruck** [comment]
@Adiolis done
