### ISSUE TITLE
City model needed?

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#83]
Well, we have no model for the cities right now.
Is this intended?
Also for our api docs it is strange that we do not provide information how the data looks like.

**Comment by kordianbruck** [comment]
Yea, definitely a good idea!

**Comment by kordianbruck** [comment]
Wait, we do have one here: https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/cities.js

I'm using that one to do the stats...

**Comment by ghost** [comment]
Okay. I´ve been looking for city.js while editing the api doc.
Probably we should rename it, so that the naming is consistent with the other models.
