### ISSUE TITLE
Inconsistent character database 

### ISSUE THREAD

**Issue by asesselmann** [Rostlab/JS16_ProjectA#86]
Hello Project A!
We have several questions for you:

Lyonel strong has a spouse: "1st: unknown2nd: unknown3rd: unknown" 
Can you please fix that?

Why does a character have a feature parents, if it already has a mother and a father?

What does the feature book mean? By now, all characters have only one book. Is it the book of death?

Also we found that the database is not consistent.
Mothers, fathers, heirs, ... are not always listed in the characters database, although this features refer to characters.
We encountered the same problem with cultures and houses.

**Comment by sacdallago** [comment]
:D I'm gonna enjoy the conversation in this issue

**Comment by ghost** [comment]
- There should be no houses etc. in the characters db anymore with strange data anymore. @kordianbruck please, update the server.
- Parents is redundant and will be removed. Thanks.
- I haven´t modeled the book property, but it is an array. So i guess the array states the appearances of a character in the books. @theocheslerean Probably a scraper issue?
- I don´t know why non existing entries can be referenced. Nontheless, the characters and so on should exist. I will check on them, why they are not in the db. @theocheslerean 

Thanks for the reports. It is hard to validate if all entries make sense. =)

**Comment by asesselmann** [comment]
@Hack3l  @ThuyNganTran  @subburamr 
Have a look!

**Comment by asesselmann** [comment]
Had a look at feature book: only 49 characters have this feature, all others have books:[ ], which is not what we want ;)

**Comment by ghost** [comment]
Yeah, the scraper should get more out of it.
@theocheslerean ;)

**Comment by ghost** [comment]
I´ve implemented the multiple books scraping.
@kordianbruck Please, update.

**Comment by kordianbruck** [comment]
Updated. Books are in.
