### ISSUE TITLE
Incomplete Titles

### ISSUE THREAD

**Issue by ThuyNganTran** [Rostlab/JS16_ProjectA#87]
Some of the title values in the character database return incomplete titles, e.g. Tywin Lannister has the title 'Casterly Rock' even though his title should be 'Lord of Casterly Rock'.

**Comment by ghost** [comment]
@theocheslerean Any idea why the scraper returns this? I checked the cache file. The scraper gives me too less.

**Comment by ghost** [comment]
I have implemented the multiple titles for the characters. The model property is therefore now an array.

@kordianbruck Please, update. 
@theocheslerean I could not figure out, where you scrap the title property. (yeah, really :P ) 
Therefore i am overwriting it. Please remove the old implementation.

**Comment by kordianbruck** [comment]
All the characters updated on the api
