### ISSUE TITLE
Last two TV Episodes are Missing

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#88]
When fetching all the TV episodes, The last 2 ones are actually missing in the DB.
Apparently the wiki doesn't contain any information about them because the article isn't witten yet for some reason: http://awoiaf.westeros.org/index.php/Portal:TV_Show

Is there way to manually add the title, number and season information to the database?

**Comment by sacdallago** [comment]
Expand the wiki! Safest way to do this in my opinion!

**Comment by kordianbruck** [comment]
Yes, adding it to the wiki is the best approach!

**Comment by ghost** [comment]
@docjag @kordianbruck @theocheslerean @boriside @togiberlin 
Who wants to do that? =)

**Comment by togiberlin** [comment]
@Adiolis yeah, let me check it now... @kordianbruck I can take off some work off your shoulders if you want

**Comment by togiberlin** [comment]
@mbandle Ehm... `Season 6` and `Season 7` are not public, yet. `Season 6` will come out end of April 2016. The content of these brand new seasons are also in no GoT book. Please do some research before opening issues ;)
@sacdallago Close this issue?

**Comment by bandle** [comment]
Who spoke of seasons? I meant episodes
![bildschirmfoto 2016-03-19 um 23 17 30](https://cloud.githubusercontent.com/assets/11232638/13901573/d144f898-ee28-11e5-9ea8-0dc10c44400d.png)

**Comment by sacdallago** [comment]
@togiberlin you should maybe read the first message again and open up the link there :see_no_evil: just saying

**Comment by togiberlin** [comment]
Ups...lol, forget it :) it's late!

**Comment by gyachdav** [comment]
Has anyone considered integrating this as a secondary  source?

http://gameofthrones.wikia.com/wiki/Season_5#Episodes

They also have an API you can tap into.

**Comment by sacdallago** [comment]
@gyachdav yeah. @Adiolis was already taking the pic from wikia I guess, right?

**Comment by ghost** [comment]
@sacdallago 
No, i used imdb to get the cast information for the episodes and the images so far are all fetched from the awoiaf wiki.

**Comment by sacdallago** [comment]
Oh, ok. Damn where did I see that someone mentioned wikia?! Too many issues :D @kordianbruck you maybe?

**Comment by togiberlin** [comment]
@sacdallago @mbandle  I think we can close this issue. They closed down their wiki registration for new users (scroll down to bottom): http://asoiaf.westeros.org/index.php?/topic/132382-how-to-get-a-wiki-account/
I requested some senior forum member to add this information, but can't guarantee whether he'll do it in the next couple days: http://asoiaf.westeros.org/index.php?/topic/34958-the-asoiaf-wiki-thread/&page=65#comment-7511892

**Comment by gyachdav** [comment]
Not sure if we can wait for the wiki ppl to add this in. If we wont integrate the missing episodes from wikia, then maybe we should just put it into our db as an override mechanism?

The C10 map also seems to be affected. Jon Snow is still at Hardhome..

@mbandle  @AlexBeischl @tPiffrader

**Comment by sacdallago** [comment]
@gyachdav ... There's been a discussion going on on data sources :) what you just suggested is going against something we decided in the last 3 days afrer several discussions and polls, which is: data should be consistent and on the wiki.
I'll talk to the wiki owner again see what can be done

**Comment by gyachdav** [comment]
I'm all for clean solutions of course BUT [winter is coming ](http://winteriscoming.net/)

**Comment by ghost** [comment]
That are two missing episodes right?
I can add them now manually and in later parts this will be updated/overwriten by the scraper automagically.

**Comment by gyachdav** [comment]
:+1:

**Comment by kordianbruck** [comment]
I already did that. Check https://github.com/Rostlab/JS16_ProjectA/commit/6d2aded1b0df2efab7f03e71955c57680bd97b76

Working on refilling the DB.

**Comment by kordianbruck** [comment]
Now in the DB and we have all 50 episodes. We should revisit this in a month or so, if we get access to the Wiki and can actually add some data there.

**Comment by sacdallago** [comment]
@togiberlin I don't see where in that link you posted they are saying that you cannot sign up anymore?

**Comment by sacdallago** [comment]
# :dizzy: **Congratulations** :dizzy:

@togiberlin you have been successfully added as a full member to the wiki.
You can now enter the data you want to scrape there!

>   What I've done right now is created an account for the person who 
> requested it on our forum. We'd be happy to request accounts for anyone 
> else who'd like, but we'd ask that like "Togi" (his name on our forum) 
> they first create an account at http://asoiaf.westeros.org/ and then 
> send us their username and e-mail with the request for an account.

**Comment by togiberlin** [comment]
Uuuh.....connections :key: :sunglasses: 
@sacdallago [Last two episodes of season 5 is in the wiki, issue can be closed](http://awoiaf.westeros.org/index.php/Portal:TV_Show)

_P.S. in the past, if you were member of the forum, you automatically had access to the wiki. This led to a lot of spam, so they stopped auto admitting new users and switched to a manual process. Users had to have at least 3 forum posts and ask the admins for a wiki account. But this also was very spammy, as the admins had to admit every new user manually. Around fall 2015, they simply stopped admitting new users and closed the wiki to newcomers. Source: reading some posts on the forum regarding the wiki access._
