### ISSUE TITLE
Add pagination to characters request

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectA#89]
When requesting the characters api (/characters) i believe its a cool idea to add pagination (i.e. page and per_page parameter )

**Comment by gyachdav** [comment]
And why is this on A's issues?

**Comment by ghost** [comment]
For me it sounds pretty awkward to implement the pagination already on the api.
@sacdallago Isn´t it?

@mina-zaki Are you probably looking for a limit feature like in SQL? 
With start and end range?

**Comment by sacdallago** [comment]
Well, the problem is legitimate: If you were to build a webpage, you would implement pagination in the backend, becuase < data you send = faster page loading. This said, this API is thought as a standalone, thus implementing pagination (which forces the API to be _stateful_) _is_ not really relevant and an overhead.

Finally, I would say:
@mina-zaki implement this on the frontend and wait for the request to finish

**Comment by mina-kleid** [comment]
will do it on the front end. But from my point of view any RESTful api endpoint ( even if its standalone) which returns more than couple of results (in our case it returns 1900 as a start) should always provide pagination, even for performance issue(database and server). in worst case pagination should be static value, like 100 per page

**Comment by ghost** [comment]
For me something like pagination is application logic. It would not be helpful if the api already defines how many entries are on one page.

I get your problem and i think the best solution for this is providing a feature like limit in sql.
So, that you can define the starting entry and how many further entries are resent.

**Comment by kordianbruck** [comment]
You should still limit the amount of entries you return in order to not transfer one megabyte in json data each time. I think this is a good idea and should definiatly be implemented but it is out of the scope of the current project for the first release. :+1:

**Comment by sacdallago** [comment]
Yeah well, at this stage I would move more towards a websocket than simple API calls

**Comment by kordianbruck** [comment]
@sacdallago yea, we could also do this really cool thing called XYZ, but we are really running out of time :neutral_face:

**Comment by sacdallago** [comment]
ahah sure! I'm just saying!!!!!!!!!!!!!! The issue's closed, so don't panic.. I was commenting on your "out of the scope..."
