### ISSUE TITLE
Visualize the statistics: how many data points and what are they?

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#9]
- [x] Convert JSON to csv
- [x] Import data to Google Fusion Tables
- [x] Find interesting facts to GoT Characters
- [ ] Find interesting facts to GoT Episodes
- [ ] Find interesting facts to GoT Houses
- [ ] Keep statistics up-to-date with model changes as best as possible

Please check `/wikiData/statistics/`

**Comment by sacdallago** [comment]
This issue needs further explanation please!

**Comment by boriside** [comment]
How should we complete the visualisation? What datas can/ should we use?

**Comment by kordianbruck** [comment]
@sacdallago yea, I would like some better explanation as well. I've copied it from the Wiki. Maybe the tutors can figure out something more descriptive?

**Comment by sacdallago** [comment]
Sorry for taking so long to answer: My take is count the number of data in each collection (character, houses, episodes, battles,...) and give an API call that returns these statistics.
I say **my take** as this was written by @gyachdav on the wiki, maybe he had something else in mind, if so he will contradict me and let you know!

**Comment by gyachdav** [comment]
The idea here is to give some interesting statistics not easily fetched from just looking at the wiki. 
Some examples related to characters:
- age histograms
- number of characters per house
- male/female ratios
- distribution of skills 
- other items you deem interesting 

@goldbergtatyana who suggested this item may also contribute some ideas.

**Comment by togiberlin** [comment]
ok, got it

**Comment by goldbergtatyana** [comment]
Yes, exactly, these are the points that could be visualized. However, there can also be many more others (distribution of male/female characters, dead and alive characters, etc.). So, the idea was that you visualize the statistics that ~you~ find interesting in a similar way that was done here: http://www.sisense.com/dashboards/game-of-thrones/

**Comment by togiberlin** [comment]
Ok, but this depends on the success of importing the data to MongoDB. We hope, that there still will be room to do the statistical stuff. Thx for the Dashboard suggestion. Looks nice

**Comment by ghost** [comment]
Something in progress, here?

**Comment by togiberlin** [comment]
@adiolis Yeah, let me finish it this weekend.

**Comment by kordianbruck** [comment]
First stats can be looked at here: https://got-api.bruck.me/api/stats

@.everyone: lets hear some suggestions what might be interesting! :+1:

**Comment by sacdallago** [comment]
Let me start with: https://www.youtube.com/watch?v=j45x9ranFH0
Second off: if you, @kordianbruck start even just thinking about implementing the visualization part which **F** should do I wil

> [cut you up so bad, you gonna wish I no cut you up so bad](https://www.youtube.com/watch?v=1EyMGt1M-Rs)

No, but srsly: **F**s job! :)

**Comment by kordianbruck** [comment]
@sacdallago I already have, but it's not pushed yet :P (but pssst, don't tell anyone)

**Comment by kordianbruck** [comment]
Will continue in other issue as we actually have nothing to do with 'visualization'.
