### ISSUE TITLE
Top Plod characters return 404

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectA#93]
when calling the get top plod characters, the response content is fine but the response status code is always 404. I believe because it is in the same routes as characters 
example : https://got-api.bruck.me/api/characters/plod/3

**Comment by boriside** [comment]
@mina-zaki you mean: {"message":"Failure. No character with that data existing!",... ?

**Comment by mina-kleid** [comment]
yeas and also the status code of the response is 404(not found) instead of 200(Ok)

**Comment by boriside** [comment]
yeah we should wait for the server :P

**Comment by sacdallago** [comment]
It would be wise if for testing you run the API locally (localhost) and don't rely too much on DDOSing @kordianbruck 's machine :D Maybe he can just tell you what the config looks like for you to run it locally (aka mongo and all the other things [here](https://github.com/Rostlab/JS16_ProjectA/blob/master/cfg/config.json.template))

**Comment by kordianbruck** [comment]
Server is back up :heart:

**Comment by mina-kleid** [comment]
As mentioned before the response content is fine, but the status code of the response is 404 instead of 200 (you can see it on the top right corner). 

![screen shot 2016-03-19 at 19 43 02](https://cloud.githubusercontent.com/assets/1983476/13900623/d21d7560-ee0a-11e5-9ef7-db820137dfa0.png)

**Comment by togiberlin** [comment]
@mina-zaki ok, let me check that

**Comment by ghost** [comment]
Why exactly 404 is wrong here? It just states NotFound, what is here the case.
Am i missing something?

Or is that in data not the data provided by the request and the correct response out of the db?
If so, then there should be more data sent back...

**Comment by mina-kleid** [comment]
@Adiolis yes because this is the whole error handling of all responses. response with 404 means its an error and i shouldnt process it. response of 200 means success and i can process it.

**Comment by ghost** [comment]
Ah, i didn´t know that getByPLOD is filtering properties. So for me the response data was strange ;)

@togiberlin stores/charaters.js getByPLOD is implemented wrongly. If you do not delegate to get() you have to define the callback differently. See get() for the right callback for getByPLOD.

**Comment by togiberlin** [comment]
@Adiolis I hope it should work now

**Comment by mina-kleid** [comment]
Works perfect now, thanks
