### ISSUE TITLE
DANGERZOOONE

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#95]
Hey guyz,
isn't [this](https://github.com/Rostlab/JS16_ProjectA/blob/master/cfg/config.json.template#L20) a little bit [DANGERZONE-ish](https://youtu.be/RRU3I_o1vLc?t=42s)?

You know that in [package](https://github.com/Rostlab/JS16_ProjectA/blob/master/package.json) you can define different `scripts` which can be, for example, different entry points for you app, so that instead of firing the app up and having the wrong value in the config, you just `npm resetApp` to, for example, "delete collection and refill"

**Comment by julienschmidt** [comment]
`npm run resetApp`. There are just a few shortcuts for `start`, `test` etc :wink:

**Comment by sacdallago** [comment]
Oh yeah sorry, that's what I meant :D

**Comment by ghost** [comment]
If i only knew that earlier :P.
Will change the filling actions to scripts...
Thanks for the hint.

**Comment by ghost** [comment]
npm run refill --collection=x
 now to delete and fill.
Will later put information on the readme.

**Comment by kordianbruck** [comment]
What exactly is the danger zone? You have linked the file in master not in the commit where the problem is actually added @sacdallago - please enlighten me <3

**Comment by ghost** [comment]
@sacdallago @kordianbruck 
Okay. All scripts are implemented:

Policy 1: Delete collections and fill all (_id changes!)
npm run refill --collection=x

Policy 2: Update all entries and add new ones. (_id is constant here)
npm run update --collection=x

Policy 3: SafeUpdate, where old entries are not updated. Only new properties/entries added.
npm rum safeUpdate --collection=x

**Comment by sacdallago** [comment]
FIY @kordianbruck https://github.com/Rostlab/JS16_ProjectA/blob/5bcd7f5085537367b9f714389c8687d09f07ceca/cfg/config.json.template#L20

**Comment by kordianbruck** [comment]
Gotch ya, thanks!

So fillers are basically gone from the API - great!
