### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#97]
Hey, why don't you modernize a bit and start multithreading the shit out of the API?

Again, free to _get inspired_ by https://github.com/sacdallago/pssh/blob/master/index.js

**Comment by ghost** [comment]
@kordianbruck feel free :P

**Comment by kordianbruck** [comment]
@sacdallago is this not part of DevOps responsibilities (The guy that sets up the _production_ server)

**Comment by sacdallago** [comment]
I would have to touch your code!
That would make me feel so close to you :heart: :heart: :heart: 
So. Close.  

You sure you wanna see me **that close**.

**Comment by kordianbruck** [comment]
@sacdallago remember our first kiss? :kissing_heart:

**Comment by sacdallago** [comment]
How could I possibly forget, I'm offended.

**Comment by theocheslerean** [comment]
That's real bromance :heart_eyes:

**Comment by ghost** [comment]
So, is this issue still an issue or can be closed?

**Comment by kordianbruck** [comment]
I'll take a look in a sec...
